### ISSUE TITLE
Test Runner

### ISSUE THREAD

**Issue by captainrdubb** [rangav/thunder-client-support#312] opened 2021-09-02 18:13 UTC
Purely a feature request, not related problem.

A console app that runs collections and returns results that include details about failure.

Postman has a tool called [Newman](https://learning.postman.com/docs/running-collections/using-newman-cli/command-line-integration-with-newman/#:~:text=Newman%20is%20a%20command%2Dline,directly%20from%20the%20command%20line.&text=Newman%20maintains%20feature%20parity%20with,the%20collection%20runner%20in%20Postman.)

**Comment by rangav** [comment] 2022-01-16 04:34
Duplicate of #98

**Closed by rangav** 2022-01-16 04:34 UTC
