### ISSUE TITLE
Exporting Collection to Postman v2 format

### ISSUE THREAD

**Issue by mikaelsand** [rangav/thunder-client-support#375] opened 2021-10-20 07:35 UTC
**Is your feature request related to a problem? Please describe.**
When testing APIs some developers may favor TC and some Postman. I know I can import Postman collection in TC but there is no way to export TC collections _to_ Postman v2.

**Describe the solution you'd like**
Being able to export collections so that they can be used by Postman favoring developers.

**Describe alternatives you've considered**
Not using TC.

**Comment by luisfernandomelon** [comment] 2021-12-01 14:11
Hello @rangav! Is there any thought about it? Is on the roadmap of TC?

**Comment by rangav** [comment] 2021-12-01 14:17
Hi @luisfernandomelon, yes it’s in roadmap

**Comment by rangav** [comment] 2022-01-15 20:50
I am closing this issue, as it's duplicate of #162

**Closed by rangav** 2022-01-15 20:50 UTC

**Comment by rangav** [comment] 2022-02-16 18:47
This feature is now implemented in v1.12.0

Read 3rd point here for details
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.0

please let me know if any feedback

**Comment by luisfernandomelon** [comment] 2022-02-17 07:08
Hello @rangav thank you so much for the latest version.

**Comment by rangav** [comment] 2022-02-17 07:27
@luisfernandomelon you are welcome 👍

Let me know if any feedback or suggestions to further improve the product
