### ISSUE TITLE
Renamed requests reverts to old name after being sent

### ISSUE THREAD

**Issue by xerosugar** [rangav/thunder-client-support#378] opened 2021-10-25 13:57 UTC
**Describe the bug**
If you rename a request, then send it, the name changes back to what it was before it was sent.

**To Reproduce**
- Create a new request, click the three dots in the bottom right corner -> Rename -> Type a new name.
- Send the request.

**Expected behavior**
Name shouldn't change.

**Platform:** 
 - OS: Win 10
 - vscode version: 1.61.1
 - extension version: 1.9.1

**Comment by rangav** [comment] 2022-01-15 15:55
Hi @xerosugar i cannot reproduce the bug, can you provide detail steps

**Comment by xerosugar** [comment] 2022-01-18 09:03
Sorry, I don't have this extension installed anymore so I cannot test it.

**Comment by rangav** [comment] 2022-01-18 09:20
Ok no problem, I am closing this issue then.

feel free to re-open if needed.

**Comment by rangav** [comment] 2022-01-18 10:09
Hi @xerosugar just now re-tested the steps you said, in activity tab, I can re-produce the issue.

Will fix in the next update asap

**Comment by rangav** [comment] 2022-01-26 12:30
This bug is now fixed in v1.11.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.11.0

please let me know if any feedback

**Closed by rangav** 2022-01-26 12:30 UTC
Labels: bug, Priority
