### ISSUE TITLE
Authorization Code flow with PKCE

### ISSUE THREAD

**Issue by muziekklas** [rangav/thunder-client-support#386] opened 2021-11-02 10:45 UTC
**Describe the solution you'd like**
Postman is able to support Authorization Code flow with PKCE (Sha256) as an authorization flow. 
This could be a contributing factor for us to choose your plugin, which is by the way a neat alternative over postman.

**Describe alternatives you've considered**
Maybe create an open-source Authentication module, so people can add new authentication methods / grant types.

**Implementation:**
Take a look at how postman solves this:
![image](https://user-images.githubusercontent.com/4663179/139832218-6ddc80cb-62d7-4374-b822-97682bb191f4.png)
In the nodejs community there are many solutions of fetching tokens using Code flow + pkce. I don't know which library you currently use but maybe it has out-of-the-box support for it. 

Keep up the good work!

**Comment by rangav** [comment] 2021-11-02 10:52
Thanks @muziekklas for feedback, will add to roadmap

**Comment by rangav** [comment] 2022-01-15 15:37
Duplicate of #287

**Closed by rangav** 2022-01-15 15:37 UTC

**Comment by rangav** [comment] 2022-07-06 18:17
This feature is now implemented and published to marketplace, please update to v1.16.6

See all features and bugs fixed released
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.6
