### ISSUE TITLE
Cannot detect custom filter

### ISSUE THREAD

**Issue by huangtaizia** [rangav/thunder-client-support#1240] opened 2023-07-29 11:29 UTC
**Describe the bug**
Thunder client cannot detect custom filter after choose custom script after re-type command: module.exports (happens both in Sublime Text and VS Code).Create new custom filter (axactly the same code of 'preFilter1')

**To Reproduce**
1. Copy fuction 'preFilter1' from custom-filter.js file
2. Comment command: module.exports = [...] by Ctrl + /
3. Re-type exactly this command (using sublime text or vs code. Both of it install JavaScript snippset)
4. Save this custom script and add to "Script" from Collection Setting
5. Change to the request tab (http://httpbin.org/anything) > click "Reload Data"
6. Click to tab "Pre Run" > Click select "Pre Request Scripts"

**Expected behavior**
Can detect all module exports from module.export = [....] to select script

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.80.2
 - extension version: v2.9.3

**Your Team Size Using TC:**
- 

https://github.com/rangav/thunder-client-support/assets/87369967/b429c20f-01ec-4ffd-96af-ab99b31afac9

- Only me

**Comment by rangav** [comment] 2023-07-29 11:58
Hi @huangtaizia 

Its `module.exports = []` not module.export

**Comment by huangtaizia** [comment] 2023-07-29 13:30
Yep. That my typo mistake. But in the custom script, I did right command. You can watch attached video to detail

**Comment by rangav** [comment] 2023-07-29 13:32
I think the problem is you have 2 module.exports lines one as comment

remove the comment line with module.exports then it will work.

I am using regex to get function names from script file without executing the script to show as dropdown in request view

**Comment by huangtaizia** [comment] 2023-07-30 08:39
Yep, that's correct. The comment line is reason. I tried to removed this line, then it worked fine. But I found the other issue: When I use moment module to use for a variable, and Thunder client cannot read that code. But when I changed to use new Date(), the script work fine. You cant watche the attached video for detail.

https://github.com/rangav/thunder-client-support/assets/87369967/7e7d11f5-cbe3-4c14-bb6c-5dfb9846f3dd

**Comment by rangav** [comment] 2023-07-30 09:01
`moment` is not built in library, you need to load it separately 

see docs for using node modules 
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#import-node-module

**Comment by rangav** [comment] 2023-07-30 09:03
One more thing, you don't need to click `reload` icon in sidebar, when you change script file. The extension will auto load data.

**Comment by rangav** [comment] 2023-07-31 12:02
This bug is fixed now and published to the marketplace, please update to `v2.10.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.10.0

Please let me know your feedback.

**Closed by rangav** 2023-07-31 12:02 UTC
Labels: bug
