### ISSUE TITLE
[Support] Please release Thunder Client to VScodium

### ISSUE THREAD

**Issue by kevinadhiguna** [rangav/thunder-client-support#317] opened 2021-09-07 10:10 UTC
Hi, thank you for your very nice work on Thunder Client!

I hope it will be available on [VS codium](https://vscodium.com/) as well.

![image](https://user-images.githubusercontent.com/43397636/132327308-86849ba3-6cb0-4bb0-a0b4-805f098465cb.png)

Thank you

**Comment by rangav** [comment] 2021-09-08 14:42
Hi @kevinadhiguna duplicate of #30

**Closed by rangav** 2021-09-08 14:42 UTC

**Comment by rangav** [comment] 2022-02-02 17:21
Hi, finally managed to publish to open-vsx, now you can download from extensions tab
https://open-vsx.org/extension/rangav/vscode-thunder-client

**Comment by kevinadhiguna** [comment] 2022-02-08 03:41
Cool, much appreciated @rangav !

![image](https://user-images.githubusercontent.com/43397636/152913860-ecf9f7f6-8f5b-4935-857b-5074bca2d86f.png)
