### ISSUE TITLE
Feat request

### ISSUE THREAD

**Issue by shahul01** [rangav/thunder-client-support#274] opened 2021-07-23 13:44 UTC
Undo and redo written address
History of sent requests

Btw great job

**Comment by rangav** [comment] 2021-07-23 13:48
Hi @shahul01 undo and redo already have a issue #146

Activity tab will record your history which is already supported. are you looking something different?

**Comment by shahul01** [comment] 2021-07-23 14:14
fast response.

![image](https://user-images.githubusercontent.com/53307156/126794743-25f3ad4a-34ac-433b-8857-aca1eca06c99.png)

as you can see, my activities are empty, even though I have sent many request already

**Comment by rangav** [comment] 2021-07-23 14:17
if you sent request from a collection, it wont appear in activity, as some users asked us to disable this feature.

Click **New Request** button and execute the request.

**Comment by rangav** [comment] 2021-07-23 15:01
Let me know your suggestion about this, because different users have different use cases.

**Comment by rangav** [comment] 2021-07-25 21:08
closing this issue as it duplicate of #236

**Closed by rangav** 2021-07-25 21:08 UTC

**Comment by rangav** [comment] 2021-07-26 13:53
Provided new vscode setting **Show Activity From Collection**  in v1.8.0

see all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.8.0
