### ISSUE TITLE
Attached and Global Envs are not used by client

### ISSUE THREAD

**Issue by PascalRauprecht** [rangav/thunder-client-support#480] opened 2022-02-25 07:47 UTC
**Describe the bug**
Hi,

I created a Global Env and added a "token" variable. Fetch token request is writing the token into the global env variable. However, I cannot figure out how to use this variable in consecutive requests. Using {{token}} or using {{token, global}} does not seem to work. 

How can I use those global variable values? Any suggestions would be highly appreciated. 

As a general note: Great VS code extension! A big thank you to everyone who contributed to it.

**To Reproduce**
Create a global env variable. Set it via one request. Try to read it for another request.

**Expected behavior**
Global env variable in the second request should be processed.

**Platform:** 
 - OS: Windows
 - vscode version: 1.64.2
 - extension version: v1.12.1

**Solution:**
No idea, unfortunately

**Comment by rangav** [comment] 2022-02-25 08:53
Hi @PascalRauprecht

You can use global env variables using the same format `{{token}}`

if the same variable is present in active environment, this will override global value.



see the screenshot below, using the url https://httpbin.org/anything
<img width="1224" alt="Screenshot 2022-02-25 at 08 51 09" src="https://user-images.githubusercontent.com/8637550/155684981-8e315792-4f04-4efd-a92d-491d348944a1.png">

**Comment by PeterDomC** [comment] 2022-02-25 10:40
Hi,

I have the same issue as @PascalRauprecht (same OS and version).
When I use a global env variable in a request as a query parameter or in the body,
Thunder Client does not seem to detect the variable properly.
It does not turn "green" like for variables from a "usual" env.
Can you help us out?

Best regards and thanks for this great extension :)
Peter

**Comment by rangav** [comment] 2022-02-25 10:46
Hi @PeterDomC thanks for reporting the issue, can you share screenshots of the issue if possible

**Comment by PeterDomC** [comment] 2022-02-25 11:14
Hi @rangav .
Thank you for the quick respond. Here is a screenshot where the variable from the global environment does not turn "green".
<img width="695" alt="globtoken" src="https://user-images.githubusercontent.com/80814965/155705999-4f19a2da-724f-4be4-af71-19bfd3ac97a3.png">

**Comment by rangav** [comment] 2022-02-25 11:32
Hi @PeterDomC, its wokring for me

![Screenshot 2022-02-25 at 11 30 45](https://user-images.githubusercontent.com/8637550/155708273-69461d70-0536-4374-9e86-353a25b560ac.png)

**Comment by rangav** [comment] 2022-02-25 11:34
@PeterDomC can you test with this url https://httpbin.org/anything and execute the request 

use any sample global env variable.

**Comment by PeterDomC** [comment] 2022-02-25 12:07
I did the request with the given url. The problem persists:
<img width="1014" alt="glob2" src="https://user-images.githubusercontent.com/80814965/155712501-c3d03006-c714-4368-b1c4-8019a2024bb5.png">

**Comment by PeterDomC** [comment] 2022-02-25 12:14
By playing around, I found the reason for the behavior.
It seems that having a global and a local env causes the problem.
When I delete my local env, it works - Thunder Client detects the variables properly.

Although my local env did not contain any variables, it seemed to outplay my global env.
Should it be possible to use global and local env at the same time?

**Comment by rangav** [comment] 2022-02-25 12:19
Let me verify that and get back to you

**Comment by rangav** [comment] 2022-02-25 15:58
Hi all, I can confirm that this a bug, when Local Env is created, global env variables not working. 
Thanks for reporting the issue.

Will fix it asap.

**Comment by PascalRauprecht** [comment] 2022-02-25 16:31
Thanks for looking into the bug :)

**Comment by rangav** [comment] 2022-02-25 17:49
This bug is now fixed in v1.12.2

see all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.2

**Closed by rangav** 2022-02-25 17:49 UTC
Labels: bug

**Comment by PeterDomC** [comment] 2022-02-25 20:20
Thanks a lot for fixing it! :)
