### ISSUE TITLE
[feature request] Supporting up-down layout 

### ISSUE THREAD

**Issue by caperso** [rangav/thunder-client-support#169] opened 2021-05-21 02:15 UTC
Hey guys, I hope this great tool can support up-down layout.
Since I used to split my vscode into left-right views,
I found that using the thunder-client in one view can be a litte narrow to display
Specially for the url input, when the url is really long 

![image](https://user-images.githubusercontent.com/34877623/119072001-581c4e00-ba1d-11eb-889a-d0ea97e98879.png)

**Comment by rangav** [comment] 2021-05-21 02:30
Hi @caperso duplicate of #99

**Closed by rangav** 2021-05-21 02:30 UTC

**Comment by rangav** [comment] 2021-07-13 11:51
This feature is now implemented in v1.7.0
https://github.com/rangav/thunder-client-support/releases/tag/1.7.0
