### ISSUE TITLE
#1154 breaking DataFiles with v2.7.4?

### ISSUE THREAD

**Issue by KingofGnome** [rangav/thunder-client-support#1198] opened 2023-06-14 16:02 UTC
**Describe the bug**
I'm wondering what happend here:
"Can we have variables with object support in data file / env file?" #1154

I had perfect support for nested objects in my dataFile for a year or so, having a DataFile for my Collection like this:

```json
[
  {
  "id": 0,
  "test_template": "test_template_xy",
  "test_data": {
    "company": [
      {
        "name": "companyA"
      },
      {
        "name": "companyB"
      }
    ],
    "job": [
      {
        "name": "IT-Service"
      },
      {
        "name": "SoftwareDevelopment"
      },
      {
        "name": "Hardware-Service"
      }
    ]
  }
},
{
    "id": 1,
    "test_template": "test_xyz",
    ....
},
{...}
]
```
and running my Test-Collection with a json body like this
```json
{
  "template": "{{test_template}}",
  "data": "{{text_data}}"
}
```

and with one of the latest Updates (probably https://github.com/rangav/thunder-client-support/releases/tag/v2.7.4 with change #1154 ) now suddenly thunder sends requests like this, Request Body:

```json
{
  "template": "test_template_xy",
  "data": "{"company":[{"name":"companyA"},{"name":"companyB"}],"job":[{"name":"IT-Service"},{"name":"SoftwareDevelopment"},{"name":"Hardware-Service"}]}"
}
```

Any ideas, am i doing something wrong?

**Platform:** 
 - OS: Windows
 - vscode version: 1.76.0
 - extension version: v2.7.6

**Comment by rangav** [comment] 2023-06-14 16:31
Thanks @KingofGnome for reporting the bug, Will investigate and get back to you asap.

**Comment by rangav** [comment] 2023-06-14 16:34
Is it possible to test and share the result extension version `v2.7.3`, so we can compare.

**Comment by KingofGnome** [comment] 2023-06-14 21:08
I'll try, never installed a specific version with vscode, but ill figure it out ;)

**Comment by rangav** [comment] 2023-06-14 21:09
not vscode, just install an older version of the extension to test

**Comment by KingofGnome** [comment] 2023-06-15 06:02
Yeah, on Extension-Version v2.7.3 setup works just fine.

**Comment by rangav** [comment] 2023-06-15 06:04
Thanks for confirming. Will verify and fix it asap

**Comment by KingofGnome** [comment] 2023-06-15 06:07
And broken on v2.7.4 :
![grafik](https://github.com/rangav/thunder-client-support/assets/12382400/d74dbb83-1aad-4606-a334-0ad4f7885f5c)


For whatever reason while reading the data it puts the first { into extra "":
and therefore service responds correctly  with:
```json
{
  "message": "Unexpected token c in JSON at position 67"
}
```

**Comment by rangav** [comment] 2023-06-15 12:56
@KingofGnome 

In version `v2.7.3`, support for objects is not available, below is the response when data file variables are objects

<img width="1216" alt="Screenshot 2023-06-15 at 13 38 48" src="https://github.com/rangav/thunder-client-support/assets/8637550/0b888d36-a76b-496a-aad0-2f8a8bbc4a8c">

**Comment by rangav** [comment] 2023-06-15 12:59
From version `v2.7.4`, If you want proper JSON in the variables, then you should `remove quotes` around the variables.

```json
{
  "template": {{test_template}},
  "data": {{text_data}}
}
```

**Comment by rangav** [comment] 2023-06-15 20:09
- That is how the variable should work, if its a string they go inside quotes `"{{var1}}"`
- If it's a number or object then use directly without quotes `{{number}}`
- ignore the JSON error, we will fix the syntax error soon.

**Comment by rangav** [comment] 2023-06-16 09:25
I am closing the issue, as it's not a bug.

**Closed by rangav** 2023-06-16 09:25 UTC
Labels: bug, Priority

**Comment by rangav** [comment] 2023-06-27 11:09
We have fixed the JSON validation syntax error for Environment variables in v2.8.0


See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.8.0

Please let me know your feedback.
