### ISSUE TITLE
Show variable values on mouse-over

### ISSUE THREAD

**Issue by spg-iwilson** [rangav/thunder-client-support#791] opened 2022-09-23 00:11 UTC
Show a tooltip with the value of a variable when you mouse-over it. Currently the tooltip shows the word "value" when you mouse-over in the request panel. 

This should also work for variables in the request URL. Currently this shows "Enter Request URL" on mouseover, regardless of whether you mouseover a variable or any other part of the request url field.

**Comment by rangav** [comment] 2022-09-23 04:15
@spg-iwilson thanks for the feedback

duplicate of #184

**Closed by rangav** 2022-09-23 04:15 UTC
Labels: feature request

**Comment by rangav** [comment] 2022-10-03 16:41
This feature is now implemented and published to marketplace, please update to `v1.19.4`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.4

Please let me know your feedback.

**Comment by spg-iwilson** [comment] 2022-10-05 06:09
Looks great, it seems to work in most places. However I've noticed it doesn't work in the JSON Body. Can it be added there too?
________________________________

**Comment by rangav** [comment] 2022-10-05 17:10
@spg-iwilson its in my list, that needs different implementation for editors.
