### ISSUE TITLE
Import JSON file from Thunder Client to Postman

### ISSUE THREAD

**Issue by akbarsaladin36** [rangav/thunder-client-support#303] opened 2021-08-24 03:28 UTC
Hey, sir

Thank you for creating this extension that make me test an API easier. I want to ask a question for you. How to import JSON file from Thunder Client to latest Postman ? Because i have some error that said "Postman Collection Format v1 is no longer supported and can not be imported directly. You may convert your collection to Format v2 and try importing again." when i want to upload my json file from thunder client to the latest postman.

**Comment by rangav** [comment] 2021-08-24 08:07
Hi @akbarsaladin36 the exported json is in Thunder Client format. So it won’t work in postman.

Duplicate of #162

**Closed by rangav** 2021-08-24 08:07 UTC

**Comment by akbarsaladin36** [comment] 2021-08-24 08:41
Okay. Thank you sir. I hope Json format in Thunder client can supported in postman.
