### ISSUE TITLE
Import postman collections and curl

### ISSUE THREAD

**Issue by WandersonAlves** [rangav/thunder-client-support#1] opened 2021-04-01 03:39 UTC
Hi! 

Maybe you can add a feature that import a collection from postman json files? Also, a import from `curl` would be nice :D

Nice project 🚀

**Comment by WandersonAlves** [comment] 2021-04-01 03:41
Nvm, i have found that this feature exists!

**Comment by rangav** [comment] 2021-04-01 05:02
Postman is supported already, Curl support in the roadmap.

**Comment by JamesWatling** [comment] 2021-04-06 16:12
I noticed that postman imports don't include the body of the request.

It is included in the json export, but not importing correctly into ThunderClient.

Do you want me to provide a sample file, happy to do so if you can't reproduce

**Comment by rangav** [comment] 2021-04-06 16:20
can you share a sample file, that can reproduce the issue, so I can test it.

Import project is separated, if you want to check out the code and find the issue.
https://github.com/rangav/thunder-imports

**Comment by rangav** [comment] 2021-04-07 18:14
Postman body issue now fixed

This is now implemented in v1.0.6, please update extension.
https://marketplace.visualstudio.com/items/rangav.vscode-thunder-client/changelog

**Closed by rangav** 2021-04-07 18:14 UTC
