### ISSUE TITLE
Adding client certificates like key,crt, pfx ,hostname and passphrase

### ISSUE THREAD

**Issue by muhammedayman** [rangav/thunder-client-support#172] opened 2021-05-22 20:03 UTC
**Is your feature request related to a problem? Please describe.**
i'm facing issues with my requests , becuase i'm using some certificates along my http request

**Describe the solution you'd like**
We need an option like adding pfx,key hostname passphrase support option for adding ceritificates

![image](https://user-images.githubusercontent.com/4961676/119239461-e2bc9480-bb66-11eb-81fc-7fc191a0e082.png)

**Comment by rangav** [comment] 2021-05-22 20:48
Hi @muhammedayman duplicate of #130

**Closed by rangav** 2021-05-22 20:48 UTC
