### ISSUE TITLE
CMD+V paste not working on macOS

### ISSUE THREAD

**Issue by logicelf** [rangav/thunder-client-support#124] opened 2021-05-06 10:13 UTC
**Describe the bug**
The 'paste' key combo does not insert the clipboard contents into the request URL field

**To Reproduce**
- Copy a request URL to the clipboard
- Open Thunder Client
- Place cursor in request URL field
- Hit CMD+V
- Nothing happens

NB:
- Selecting the current text and copying with CMD+C or cutting with CMD-X from this field works as expected. Pasting with CMD+V does not
- Selecting [Edit > Paste] from the menubar works as expected

**Expected behavior**
The contents of the clipboard should be inserted into the text field

**Platform:** 
 - OS: macOS Big Sur 11.3
 - VS Code 1.56

**Solution:**
Unknown at present. All other VS Code text fields accept pasting with CMD+V

**Comment by rangav** [comment] 2021-05-06 10:29
Hi @logicelf some other users also complained about copy/paste not working. Will look init it.

**Comment by logicelf** [comment] 2021-05-06 12:45
Superb, thanks @rangav - and thanks for your work. Superb extension to have for debugging API queries.

**Comment by rangav** [comment] 2021-05-06 12:48
@logicelf glad to know you like it 👍.

**Comment by zigang93** [comment] 2021-05-19 17:45
m1 mac with same issue..

**Comment by rangav** [comment] 2021-05-19 18:13
There is additional processing happens after paste event, may be there is some error in that.
I will verify and fix that in the next update.

**Comment by rangav** [comment] 2021-05-21 16:55
Hi guys, can anyone try to paste in `body` tab and text filed and see it’s working or not?

**Comment by logicelf** [comment] 2021-05-22 07:05
Hi @rangav - cannot paste in `body` tab (or `Request Url`). Using Thunder Client 1.3.0 (assuming latest as no updates found).

**Comment by rangav** [comment] 2021-05-22 07:40
Thanks @logicelf for confirmation.

**Comment by rangav** [comment] 2021-06-01 20:03
Hi I cannot find any issue in code related to this, as it is working for me on my Mac.

Try these suggestions in the links below, as they have similar issue
https://stackoverflow.com/questions/51521004/in-visual-studio-code-ctrlv-is-not-working
https://stackoverflow.com/questions/52318042/cmdc-is-not-working-on-visual-studio-code
https://github.com/microsoft/vscode/issues/51018

**Comment by logicelf** [comment] 2021-06-02 12:19
Hi @rangav

Thanks for this - I have now found the culprit. The following were all dead ends:

- Keybindings are correct (a search of prefs shows only the default ones for `cmd+v`, with no entries for `cmd+v` in the `keybindings.json` overrides file)
- Nothing shows up in terminal (or anywhere else that I can see)
- `cmd+v` works perfectly everywhere else in VS Code (files, terminal, search, all other extensions)

However, I did look through my other extensions and disabled '[Indent on Paste](https://github.com/gazugafan/vscode-indent-on-paste)' - which fixed the issue. It's presumably intercepting the paste event, but I've played around and it doesn't add any new keybindings.

Odd that it doesn't affect anything but the text fields in your extension. Developer informed:

https://github.com/gazugafan/vscode-indent-on-paste/issues/19

Thanks again!

**Comment by rangav** [comment] 2021-06-02 12:39
Thats super @logicelf👌  Thanks for finding the issue. Let see if other users have similar problem.

**Comment by rangav** [comment] 2021-06-24 05:38
I am closing this issue, feel free to re-open if needed.

**Closed by rangav** 2021-06-24 05:38 UTC
Labels: bug

**Comment by jdgamble555** [comment] 2022-03-04 02:24
This is still an issue on WIndows... super frustrating!

**Comment by rangav** [comment] 2022-03-04 04:58
Hi all, the request url and other fields are not standard `input` fields, they are `contentEditable` Fields, so they lost all the standard functionality like copy paste etc..

have to build all that functionality from scratch now. Hope you all understand why it's not working 

if anyone knows the implementation, please share it here. Or when I find time I will look into it. There are lots of things on my list.

**Comment by jdgamble555** [comment] 2022-03-04 05:32
Maybe this helps:

https://stackoverflow.com/questions/2176861/javascript-get-clipboard-data-on-paste-event-cross-browser/2177059#2177059

J

**Comment by rangav** [comment] 2022-03-04 09:44
@jdgamble555 this could be vscode issue, 

can you please create a new issue for this, we can discuss there?

**Comment by Amundeep-Dhaliwal** [comment] 2022-12-16 12:11
MacOS VSCode version 1.74.0
Experiencing a similar issue whereby pasting into the response box pastes to the terminal instead.
Have adjusted the key bindings for copying and pasting. Oddly the undo binding works as intended.
