### ISSUE TITLE
Add Indicator of which ENV is active

### ISSUE THREAD

**Issue by amirzahavi** [rangav/thunder-client-support#286] opened 2021-08-02 08:55 UTC
**Describe the solution you'd like**
Currently I need to go the Env tab to check which ENV is currently active.
I would like to know which ENV is active, for instance if i have a saved request in my collection with the following URL:
`{{protocol}}://{{host}}/api/users`

I need some kind of indicator to know which ENV is active, indicator can be under the URL in the request tab or/and in the Thunder Client sidebar next to the ENV tab name (e.g -  Activity | Collections | Env (DEV) )

**Comment by rangav** [comment] 2021-08-02 09:05
Hi @amirzahavi thanks for the feet

duplicate of #159

**Closed by rangav** 2021-08-02 09:05 UTC
