### ISSUE TITLE
support setting global variables & headers on the collection level

### ISSUE THREAD

**Issue by talr1** [rangav/thunder-client-support#279] opened 2021-07-26 08:05 UTC
Setting global variables & headers on the collection level is much easier than doing so on each request
especially if you have hundreds of requests

here how it is supported in postman:

for headers you can write the following in pre-request script:

```javascript
pm.request.headers.add({ key: 'Authorization', value: 'Bearer {{token}}'})
pm.request.headers.add({ key: 'Content-Type', value: 'application/json'})
```

and variables has their own tab where you can define new variables for the collection requests, and also use values from env
this is of course possible in the env itself, but sometimes you would have multiple collections running under the same env for which you would like to have the same variable but with different values, so collection variables can help

**Comment by rangav** [comment] 2021-07-26 08:21
Hi @talr1 duplicate of #33

**Closed by rangav** 2021-07-26 08:21 UTC
