### ISSUE TITLE
Setting environment variable is not working for a particular scenario

### ISSUE THREAD

**Issue by IrshadSalik** [rangav/thunder-client-support#242] opened 2021-06-29 15:02 UTC
**Describe the bug**
Setting environment variable is not working for a particular scenario. 
**To Reproduce**
1. Go to tests tab.
2. Click Select drop down & click Json query instead Set Env Variable
3. Click Action drop down & click setTo
4. Provide value as {{variable}}
5. Execute API & Verify whether variable added in the environment variable.

**Expected behavior**
Should add variable irrespective of what i choose.

**Platform:** 
 - OS: 
 - vscode version:
 - extension version:

**Solution:**

**Comment by rangav** [comment] 2021-06-29 15:04
HI @IrshadSalik It will not work, you should select `Set Env Variable` thats by design.

**Comment by IrshadSalik** [comment] 2021-06-29 15:06
> HI @IrshadSalik It will not work, you should select `Set Env Variable` thats by design.

Ok.. Can't this recongnize by itself what user wants to acheive?

**Comment by rangav** [comment] 2021-06-29 15:10
Will think about it.

**Comment by IrshadSalik** [comment] 2021-06-29 16:29
> Will think about it.

Can you give me example for Json Query-->SetTo--> ?

**Comment by rangav** [comment] 2021-06-29 16:33
SetTo option is only used for Set Env Variable, for other options it’s ignored

**Comment by IrshadSalik** [comment] 2021-06-29 16:35
> SetTo option is only used for Set Env Variable, for other options it’s ignored

If it is dynamic based on selection can't this be good?

**Comment by ADTC** [comment] 2021-07-08 14:13
@rangav it confused me too. If possible, please disable or hide the `setTo` option for every other left-side option, and enable it only (while disabling/hiding every other comparison option) for the `Set Env Variable` option.

**Comment by rangav** [comment] 2021-07-08 14:16
Hi @ADTC I am planning the same in the next update, will hide `setTo` action, and show only when `set env variable` option selected.

**Comment by rangav** [comment] 2021-07-13 11:49
This is now fixed in v1.7.0
https://github.com/rangav/thunder-client-support/releases/tag/1.7.0

**Closed by rangav** 2021-07-13 11:49 UTC
