### ISSUE TITLE
curl  format import  convert request

### ISSUE THREAD

**Issue by wchaowu** [rangav/thunder-client-support#138] opened 2021-05-10 00:44 UTC
![image](https://user-images.githubusercontent.com/131735/117592617-d6e6d080-b16b-11eb-8beb-07a1fb2a5bdf.png)

**Comment by rangav** [comment] 2021-05-10 03:47
Hi @wchaowu duplicate of https://github.com/rangav/thunder-client-support/issues/114, you can add comments in the existing issue.

**Closed** 2021-05-10 03:47 UTC
