### ISSUE TITLE
Can we Bulk edit the headers ?

### ISSUE THREAD

**Issue by dineshkapri** [rangav/thunder-client-support#71] opened 2021-04-26 17:03 UTC

**Comment by rangav** [comment] 2021-04-27 03:37
Hi @dineshkapri will add to roadmap.

**Comment by rangav** [comment] 2021-05-02 20:35
Hi @dineshkapri closing this as its a duplicate of https://github.com/rangav/thunder-client-support/issues/40

**Closed by rangav** 2021-05-02 20:35 UTC
Labels: feature request
