### ISSUE TITLE
URLs in response should be clickable

### ISSUE THREAD

**Issue by bmarinb** [rangav/thunder-client-support#1414] opened 2023-11-20 15:02 UTC
In a normal vscode editor, URLs are clickable with ctrl + click (follow link action). 
![image](https://github.com/rangav/thunder-client-support/assets/17581426/dfbc03ac-4751-425a-b322-10b5df14bfd6)

However, in response editor, this is not possible. It would be a nice feature to have.
![image](https://github.com/rangav/thunder-client-support/assets/17581426/88e5f29d-6e9c-408f-91ff-2a2c71081c4f)

**Comment by rangav** [comment] 2023-11-20 15:19
Duplicate of #353

**Closed by rangav** 2023-11-20 15:19 UTC
Labels: feature request

**Comment by bmarinb** [comment] 2023-11-20 15:22
> Duplicate of #353

Ok, it is similar but I'm not asking for creating a new thunder client request but to perform the follow link action

**Comment by rangav** [comment] 2023-11-20 15:24
You can add comments to the existing issue.
