### ISSUE TITLE
Order and Sub Group Requests in Collections

### ISSUE THREAD

**Issue by albertolotz** [rangav/thunder-client-support#54] opened 2021-04-25 21:42 UTC
**Is your feature request related to a problem? Please describe.**

Not
**Describe the solution you'd like**

I Miss a feature that I can change the order in a Collection ou create sub groups,

**Describe alternatives you've considered**

NA
**Implementation:**

AN

the extension is fantastic. grangrat

**Comment by rangav** [comment] 2021-04-25 21:44
Hi @albertolotz  - is this duplicate of #8?

**Closed** 2021-04-26 03:38 UTC
