### ISSUE TITLE
not supporting image, pdf etc..

### ISSUE THREAD

**Issue by R35007** [rangav/thunder-client-support#245] opened 2021-06-30 06:18 UTC
**Describe the bug**
I am sending the image as a response in my localhost API.
When I tried to test it, the Thunder client not showing me a image instead its showing me a junk value.

![image](https://user-images.githubusercontent.com/23217228/123910620-59378800-d998-11eb-9e2e-989ca3945403.png)

**To Reproduce**
Step 1 - Create an API that sends image. 
I am using express. so the code will look like `res.sendFile(...absolutePath);`

Step 2 - Now try to test that with Thunder Client.

**Expected behavior**

When I hit the API It must show me an image. Not just the image. What ever I send as a response It must show me.
It may be a pdf, json, png, txt, or even an html or css etc...

**Platform:** 
 - OS: Windows 10 
 - vscode version: 1.57.1
 - extension version: 1.6.1

**Comment by R35007** [comment] 2021-06-30 06:19
By the way. I love your Work. I am out of Postman Now.  Keep Going.
Thanks for creating this wonderful Tool :);

**Comment by rangav** [comment] 2021-06-30 06:24
Hi @R35007 I'am glad you love the extension. This feature is planned for next update.

duplicate of #97

**Closed by rangav** 2021-06-30 06:24 UTC

**Comment by R35007** [comment] 2021-06-30 08:22
Cool. 👍.
Waiting for the next update.

**Comment by rangav** [comment] 2021-07-13 11:51
This feature is now implemented in v1.7.0
https://github.com/rangav/thunder-client-support/releases/tag/1.7.0

Supports only images, not pdf.

**Comment by R35007** [comment] 2021-07-13 12:38
Cool. Thanks for the update.

Just a suggestion.
Y can't u try the iframe method. If u implement the iframe insted of ace
editor it can just show u any files. If u just check the type of the
response and if the response is not json or any editor formate then u can
just show the iframe right.

Thanks,
Siva

**Comment by rangav** [comment] 2021-07-13 14:02
Currently using `img` tag, will check with iframe tag if its easy solution.
