### ISSUE TITLE
The text is inserted twice

### ISSUE THREAD

**Issue by CzarOfScripts** [rangav/thunder-client-support#558] opened 2022-04-19 06:56 UTC
**Describe the bug**
When pasting to "body" from the clipboard, the text is pasted twice.

**To Reproduce**
You need to paste the text in the "body" tab, whether you do it with "ctrl+v" or "RMB -> paste".

**Platform:** 
 - OS: Win 10 LTSC, version 1809, build 17763.2803
 - vscode version: 1.66.2
 - extension version: v1.16.2

**Comment by rangav** [comment] 2022-04-19 07:17
Thanks @Oliver-Patterson for reporting the bug, will look into it

**Comment by Vonamorya** [comment] 2022-07-29 11:59
I have registered first time here to write comment on this bug. This bug makes me crazy!

**Comment by rangav** [comment] 2022-07-29 13:44
@Vonamorya this bug is in my priority list, will fix asap.

**Comment by rangav** [comment] 2022-08-12 08:43
@Vonamorya I updated few libraries, seems to be working fine for me.

Can you let me know are you still having this issue?

**Comment by Vonamorya** [comment] 2022-08-12 10:16
@rangav thank you very much! You are the best!!!

**Comment by rangav** [comment] 2022-08-12 10:29
@Vonamorya welcome. 

is it working good now? can I close this issue?

**Comment by Vonamorya** [comment] 2022-08-12 10:35
hmmm... it works only at a second paste... A first paste duplicate phrase from buffer

**Comment by rangav** [comment] 2022-08-12 10:39
ok I leave this issue open, will investigate further.

**Comment by YakovL** [comment] 2022-11-15 19:04
The issue is definitely relevant. The problem is, it is not 100% reproducible though.

I'm experiencing it for quite a while: frequently the text is inserted twice when pasting:

* into the address field
* into headers fields
* not 100% sure atm, but probably also in query fields

but sometimes it is inserted normally.

This doesn't seem to depend on whether some text is selected or on the cursor position: for instance, sometimes the duplication happens even in an empty field. I suspect, it rather depends on the history of states of a field or may be multiple Thunder Client tabs are necessary to get the problem. Unfortunatelly, I haven't come up with a minimal reproducible example for you yet.

**Comment by rangav** [comment] 2023-11-01 14:04
This bug is fixed now, please update to `v2.15.0`

See all features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.15.0

Please test and let me know your feedback.

**Closed by rangav** 2023-11-01 14:04 UTC
Labels: bug, Priority
