### ISSUE TITLE
Json queries in tests are not working when response is not displayed (response size > 2Mb)

### ISSUE THREAD

**Issue by alejandrofdez-us** [rangav/thunder-client-support#1087] opened 2023-03-28 09:00 UTC
**Describe the bug**
Json queries in tests are not working when response is not displayed (response size > 2Mb).
**To Reproduce**
do a GET request to: https://data.nasa.gov/data.json
Include some test, for instance json.describedBy equal someValue

<img width="693" alt="Captura de pantalla 2023-03-28 a las 11 00 50" src="https://user-images.githubusercontent.com/19324988/228185415-657884ba-353c-46b2-aa90-499820b482ff.png">

**Expected behavior**
I expect to perform the test over the response even though it cannot display it.

**Platform:** 
 - OS: 13.2.1 (22D68)
 - vscode version:Version: 1.76.2
 - extension version:2.5.3

**Your Team Size Using TC:**
300 students per year + 7 lecturers

**Comment by rangav** [comment] 2023-03-28 09:11
Thanks for reporting the bug. 

Duplicate of #1065

**Closed by rangav** 2023-03-28 09:11 UTC
Labels: bug

**Comment by rangav** [comment] 2023-04-03 18:55
This bug is fixed now, please update to `v2.6.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.6.0

Please let me know your feedback.
