### ISSUE TITLE
Test works when run independently, but hangs when run in a collection.

### ISSUE THREAD

**Issue by SiJiL82** [rangav/thunder-client-support#407] opened 2021-11-30 15:54 UTC
I have a very basic request for an API tutorial, it just passes a JSON body to the API and gets a JSON object back as a response:
![image](https://user-images.githubusercontent.com/65114782/144080213-8969ac54-2f57-4207-b06f-0ada8ec5d0da.png)
I've added this to a collection, and if I run it independently by clicking it in the collection so it opens and click Send, it runs fine - returns instantly.
If I click "Run All" on the collection however, it hangs on the request- the StatusCode column just spins and never comes back.
The request has run - I can manually call the Sign In request in another tab and that then responds correctly, but the Thunder Client UI never comes back from the request:
![image](https://user-images.githubusercontent.com/65114782/144081191-d8a9fccc-ac1f-48b2-9fde-c6796548bacf.png)
It seems to be doing it for any POST request, the GET I've done worked fine.

Is there something I need to do to the collection config or the requests themselves that I need to do to get it working?

**Comment by rangav** [comment] 2021-11-30 16:03
Hi @SiJiL82 thanks for reporting the issue. 

Try restarting vscode and run collection.

**Comment by SiJiL82** [comment] 2021-11-30 16:31
Hi @rangav - still getting the same thing. 
I am running vscode in WSL (Ubuntu) in Windows if that makes any difference.

**Comment by rangav** [comment] 2021-11-30 16:42
Oh ok, can try locally first without WSL? 

It could be WSL issue

**Comment by SiJiL82** [comment] 2021-11-30 17:29
Just tried in a local VSCode (new copy of the code, so not running from the repo in the WSL file structure) and get the same results.

**Comment by jwmickey** [comment] 2022-01-06 22:26
I have observed this as well.  A workaround is to close the run-all tab and re-open it.

**Comment by rangav** [comment] 2022-01-07 03:24
Hi guys, can anyone share sample collection that can reproduce the error, for my testing?

You can remove any sensitive data

**Comment by rangav** [comment] 2022-01-20 20:31
Hi guys, do you still have this issue, I have released a new update `v1.10.0`, can you confirm please?

**Comment by SiJiL82** [comment] 2022-01-21 17:51
I'll try and find the API and tests I was using, it was part of a course I was doing before xmas!

**Comment by rangav** [comment] 2022-01-26 12:29
This bug is now fixed in v1.11.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.11.0

please let me know if any feedback

**Closed by rangav** 2022-01-26 12:29 UTC
Labels: bug, Priority

**Comment by jwmickey** [comment] 2022-01-27 04:05
Apologies for the delay in feedback - this does appear to be working from my observations so far.

One thing I did notice is that for one request I have a test that expects the response code to be 400, but is now failing because according to TC it is 404.  The actual response is indeed 400.

**Comment by rangav** [comment] 2022-01-27 04:19
@jwmickey thanks for confirming 

can you try re-run 1 or 2 times, sometimes it could be network issues

**Comment by jwmickey** [comment] 2022-01-27 04:22
To be clear, I am *expecting* the response to be 400.  I tried it several
times and got back a 404.  The ones where I expect a 200 are still 200.

**Comment by rangav** [comment] 2022-01-27 04:25
@jwmickey thanks for clarification 

when you run that request independently are you getting 400 or 404?

**Comment by jwmickey** [comment] 2022-01-28 03:15
I apologize @rangav, it is not 404.  The first run it shows "Error" for StatusCode.  Then I ran it independently and it showed 400 and the test passed.  Then run in collection worked as expected.

First run:
![first](https://user-images.githubusercontent.com/400616/151481199-d7e02fbd-5933-4440-bf0a-9705014ab17c.png)

Second run:
![second](https://user-images.githubusercontent.com/400616/151481217-39dc392e-bd64-4ad4-a638-3373ae275346.png)

**Comment by rangav** [comment] 2022-01-28 07:16
No problem @jwmickey good that it’s working now.

where ever there is error in run collection, mouse hover in on `Error` text, it will show error details.
