### ISSUE TITLE
Is it possible to have a Code part to easily integrate it into its code, for example in Javascript with fetch and axios

### ISSUE THREAD

**Issue by LeoCarre** [rangav/thunder-client-support#128] opened 2021-05-06 22:03 UTC
> ###  I wanted this !

_In Postman, select the request under your collection and click Code icon on the right panel to open the Code snippet tab. Select a language to view and copy your generated code snippet. Click the Gear icon to find additional configuration options based on your chosen language._

**Comment by rangav** [comment] 2021-05-07 02:34
Hi @LeoCarre duplicate of https://github.com/rangav/thunder-client-support/issues/114
Please add your comments in the existing issue

**Closed by rangav** 2021-05-07 02:34 UTC

**Comment by rangav** [comment] 2021-06-25 07:36
Code Snippet Generation initial support in v1.5.0

- Curl
- C# HttpClient
- Javascript Fetch & Axios
- Python requests & http.client

Click on icon `{ }` to see Code tab

https://github.com/rangav/thunder-client-support/releases/tag/1.5.0
