### ISSUE TITLE
Local environment variables won't be updated

### ISSUE THREAD

**Issue by kobmik** [rangav/thunder-client-support#853] opened 2022-10-24 18:48 UTC
**Describe the bug**

Local environment variables won't be updated in a second VS Code window.

**To Reproduce**

I have two collection sets locally. One in a workspace to sync it to git and the other one locally in the user directory.
As far as I understand, both windows should share the same local environment variables.

**Expected behavior**

As soon as I update a local variable in one window, it should be updated on the second one as well.

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.68
 - extension version: 1.20.1

**Comment by rangav** [comment] 2022-10-24 19:45
Hi @kobmik,

Both will have different Local Env variables as they are part of 2 separate projects.

you can try manually editing the `thunderEnvironment.json` file and update id to use same id in both the projects. 

Then reload vscode windows and check them.

**Comment by kobmik** [comment] 2022-10-25 06:23
Hi @rangav,

Both projects have already the same id for the local env variables. The variables will be refreshed after a restart of the project. It looks like the plugin doesn't recognize changes in thunderLocalEnvironment.json automatically if it is edited in a second window/project.

**Comment by rangav** [comment] 2022-10-25 07:12
@kobmik the extension will load data only once when initialisation.

if you are modifying the values, then use separate Local Environments.

this is by design, it’s not a bug.

**Comment by rangav** [comment] 2022-10-29 03:33
Closing this issue, feel free to re-open if needed.

**Closed by rangav** 2022-10-29 03:33 UTC
Labels: bug
