### ISSUE TITLE
NTLM Authentication does not attach token on 401 and resubmit similiar to Fiddler

### ISSUE THREAD

**Issue by pp6024** [rangav/thunder-client-support#1062] opened 2023-03-14 21:39 UTC
**Describe the bug**
1.  Sending a api request to IIS server with Single Sign On with NTLM
2. Responds with 401 / www-authenticate: Negotiate, NTLM

Thunder appears to ignore the second 401 with the token and then resubmit.

A second 401 / www-authenticate: Negotiate <Token> is then received.
Followed by a 200 / [Response Array]

**To Reproduce**
1.  Sending a api request to IIS server with Single Sign On with NTLM
2. Responds with 401 / www-authenticate: Negotiate, NTLM

**Expected behavior**
1. A second 401 / www-authenticate: Negotiate <Token> is then received.
2. Resend the request with token added to header
3. Return response data with 200 return.

Windows 10
 - IIS 8.5
 - vscode version:  1.76.1
 - extension version:  2.5.1

**Your Team Size Using TC:**
Just me now.  Up to 5 if adopted over Fiddler for VSC testing.

**Comment by rangav** [comment] 2023-03-14 21:41
Thanks @pp6024 for reporting the issue, will look into it.

**Comment by rangav** [comment] 2024-03-02 13:31
The issue is fixed in v2.18.0

**Closed by rangav** 2024-03-02 13:31 UTC
Labels: bug
