### ISSUE TITLE
Ability to make a web socket request

### ISSUE THREAD

**Issue by jai-dewani** [rangav/thunder-client-support#1243] opened 2023-07-31 22:22 UTC
**Please describe feature/problem details and the solution you'd like.**
I was working on a hackathon where I had to create APIs and WebSocket Servers and I was using Thunder to test the APIs but couldn't seem to find a way to make a request to a WebSocket Server, but I would love a feature in the future to make this possible so I don't have to install postman back again 

**Describe alternatives you've considered**
Installing Postman, which I earlier uninstalled after using Thunder 😆 

**Your Team Size Using TC:**
I am the only Developer on my team so as far as today: 1

**Comment by rangav** [comment] 2023-08-01 07:29
Thanks @jai-dewani for the feedback. 

Duplicate of #3

**Closed by rangav** 2023-08-01 07:29 UTC
Labels: feature request
