### ISSUE TITLE
NTLM does not work if PreAuth is needed. 

### ISSUE THREAD

**Issue by lexx182a** [rangav/thunder-client-support#582] opened 2022-05-04 03:07 UTC
NTLM authentication does not work for me, server returns 401. I think that's because pre authentication is needed. But I can't turn it on, because there is no such option.
btw, .Net HttpClient works well with my needs.

**Comment by rangav** [comment] 2022-05-04 08:06
Hi @lexx182a 

what kind of pre auth are you doing?

how you did this in other api clients?

**Comment by lexx182a** [comment] 2022-05-04 10:17
Hello, @rangav.
I've just checked it in Postman app. It works out of the box. It noticed like this "By default, Postman will extract values from the received response, add it to the request, and retry it. Do you want to disable this?"
So, I don't make any manual settings there. 
It would be great to have such abilities in Thunder Client someday, because it will help to work with Sharepoint Server api, for example. For now it don't.
Thank you.

**Comment by rangav** [comment] 2024-03-02 13:31
The issue is fixed in v2.18.0
https://github.com/rangav/thunder-client-support/releases/tag/v2.18.0

**Closed by rangav** 2024-03-02 13:31 UTC
