### ISSUE TITLE
Separate Collections to different files

### ISSUE THREAD

**Issue by jaxnoth** [rangav/thunder-client-support#574] opened 2022-04-27 14:58 UTC
**Is your feature request related to a problem? Please describe.**
We have multiple developers working on separate APIs.  Sometimes, Thunderclient does not get refreshed after a pull and the push afterwards overwrites changes made by another developer.

**Describe the solution you'd like**
Separating out each collection to a unique file would mitigate the issue.  This would also allow for better grouping if the source needs to be altered outside of the Thunderclient UI.

**Describe alternatives you've considered**
We are taking measures to refresh the Thunderclient after each pull, but this still is subject to human error.

**Implementation:**

**Comment by rangav** [comment] 2022-04-27 15:20
Hi @jaxnoth thanks for the feedback.

changes to db files reload collections automatically is in roadmap. For now you can reload by clicking the `Reload Data` icon manually

<img width="290" alt="Screenshot 2022-04-08 at 10 35 19" src="https://user-images.githubusercontent.com/8637550/162409176-a1683bcc-b338-4ec8-856c-8ca32558da5c.png">

**Comment by surfmuggle** [comment] 2022-11-08 22:49
I would love to have the option to use [multiroot-workspaces](https://code.visualstudio.com/docs/editor/workspaces#_multiroot-workspaces). 

Inside a multiroot-workspace each folder would contain one collection and its requests as a single or multiple files

### Example

For  [githubs rest apis for issues](https://docs.github.com/en/rest/issues) the Workspace file `GithubRestIssues.code-workspace` inside the root folder  `GithubRestIssues`  would look like this

```
{
  "folders": [
    {
      "path": "./Issues"
    },
    {
      "path": "./IssueAssignees"
    },
    {
      "path": "./IssuesComments"
    }
  ]
}
```

Each folder under the root folder  `GithubRestIssues`  would be a collection 

1. Folder `Issues` as a collection for all request regarding [Issues](https://docs.github.com/en/rest/issues/issues)
2. Folder `IssueAssignees` as above for [Issue assignees](https://docs.github.com/en/rest/issues/assignees)
3. Folder `IssuesComments` as above for [Issue comments](https://docs.github.com/en/rest/issues/comments)

**Comment by rangav** [comment] 2022-11-17 19:08
@jaxnoth We have implemented Auto-Reload the sidebar, when the db files change in `v2.0.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.0.0

Do you still need splitting of each collection to separate file?

**Comment by rherzfeld** [comment] 2022-11-21 14:55
I would like to point out that #457 might be a viable solution for the above request, as it would allow multiple files. Depending on the implementation, a collection could be considered as a .http file (with multiple requests) or a folder.

**Comment by jaxnoth** [comment] 2022-11-21 15:21
The Auto-Reload should fix the immediate issue we were having.  My team hasn't fully tested out the feature yet.
It would appear that others have similar request for splitting out the single file.  I look forward to seeing future developments in those areas.  Thanks for working on this!

**Comment by anantanandgupta** [comment] 2023-04-15 12:05
I came here searching for the solution for a multi root workspace. but seems that no one is having such an issue

i have a vscode workspace with multiple project folders. e.g.

```
{
  "folders": [
    {
      "name": "Web Site",
      "path": "../path1/web"
    },
    {
      "name": "APIs",
      "path": "../../path2/api"
    }
  ],
  "settings": {
    "thunder-client.saveToWorkspace": true,
  }
},
```

now I am not able to tell the thunder-client to choose a specific folder at this moment. the setting `thunder-client.workspaceRelativePath` always creates a folder with a value set in the setting relative to the first project in the array above. Eventually in case of the multi root workspace, i should be able to dictate where to load from and save to the thunder-tests folder.

[feature request] the name of the folder should be customizable say from thunder-tests -> api-test.

Please allow the selection of the workspace folder as the root of the workspace in place considering the folder at index `0` as the default workspace root.

**Comment by rangav** [comment] 2023-04-15 18:22
Hi @anantanandgupta 

When you have multiple workspaces the extension will choose the first one.

you can use `thunder-client.workspaceRelativePath` to specify a different path

example path - `../parent/folder`

**Comment by anantanandgupta** [comment] 2023-04-15 20:46
I will try the parent folder notation `../`. But the issue is that ... As shown in the example, the project folder may not have same parent. They may have different paths on my drive. I may be just aggregating two different projects located at different paths all together.

**Comment by surfmuggle** [comment] 2023-04-16 10:11
> I will try the parent folder notation `../`. But the issue is that ... As shown in the example, the project folder may not have same parent. They may have different paths on my drive. I may be just aggregating two different projects located at different paths all together.

If i understand you right than this folder and file structure would be possible with a multiroot workspace. 

``` javascript
   var multiroot-wokrspace  = {
  "folders": [
     { "path": "C:/2021/Github_http_API" }, // workspace 1  -
	 { "path": "D:/2022/GitLap_API" }, // workspace 2
	 { "path": "E:/2023/Gitea_API" }, // workspace 3
	 { "path": "F:/2024/Forgejo_API" } // workspace 4
  ],
  "settings": {}
}
```
The [absolute paths above are not working on my environment](https://stackoverflow.com/questions/76027109/). 
And based on https://github.com/microsoft/vscode/pull/97441 i am uncertain if different absolute paths are supported for every feature in vscode

**Comment by anantanandgupta** [comment] 2023-04-16 10:23
Give me 30 min and i will share how in real life it can be ... I have mac and Ubuntu. But will create a vm for windows to replicate the real life use case. By the way if you have an extension named live server, they handle this case very well by identifying the multi root workspaces. They let me choose the location from where i will be serving the content. But give me some time and i will be back with various possibilities.

**Comment by anantanandgupta** [comment] 2023-04-16 11:02
Hi @rangav 

I have prepared a short video to demonstrate the issue and a sample from other extension settings where they handle it differently, by using the project name. i have seen the other extension working even if there is no name provided in the settings of the workspace. if you need i can quickly create a video on how they handle the projects without the project name in the settings. but for now on my mac i have created a workspace, manually created 2 folders at different location on my system. so that i can show you the issue over here. the thunder client choose the first folder in the array.

[here is the link](https://youtu.be/yQ7EdWfRhhA) for the video shared on the YouTube (duration: 10min, privately shared)

**Comment by Sam-Lin-MillersLab** [comment] 2023-04-25 20:55
I think there are 2 different ideas here. 

1. Separate collections to different files.
2. multi-root workspace support. 

I don't think there is a conflict between 2 ideas. But more and more people use monorepo now and the size of collection is getting larger and larger. Obviously it will be more painful to merge if there are more team members working in a monorepo.

**Comment by joaonunogomes** [comment] 2023-05-24 14:33
Hi :) 
Plus one for separating collections into different files.
A possible approach I see is to have one folder (on the file system) for each collection with a specific `thunderclient.json`.
The structure of each `thunderclient.json` could be the same as is today.
This approach would impact (as far as I know 😄) the `thunderCollection.json` file.

## Example:
Let's say I want to have a folder with several collections. I could create a new folder on my project named `customCollectionFolder` and inside that folder have N folders for N collections, each one containing only the respective `thunderclient.json`.

My suggestion is to add a new property (`requestsFolder`) to `thunderCollection.json` entries, that defines the path of `thunderclient.json` specific to that collection.

`thunderCollection.json` example:
```
[
    {
      "_id": "63e43c94-0b3f-4456-86f6-01de3f29c8e9",
      "colName": "My Test Collection 1",
      "requestsFolder": "./collections/my-test-collection-1", -> contains one file "thunderclient.json" with all requests related data
      "created": "2023-05-04T08:52:11.016Z",
      "sortNum": 65000,
      "folders": []
    }, 
    {
      "_id": "63e43c94-0b3f-4456-86f6-01de3f29c8e9",
      "colName": "My Test Collection 2",
      "requestsFolder": "./collections/customCollectionFolder/my-test-collection-2", -> contains one file "thunderclient.json" with all requests related data
      "created": "2023-05-04T08:52:11.016Z",
      "sortNum": 65000,
      "folders": []
    },
    {
      "_id": "63e43c94-0b3f-4456-86f6-01de3f29c8e9",
      "colName": "My Test Collection 3",
      "requestsFolder": "./collections/customCollectionFolder/my-test-collection-3", -> contains one file "thunderclient.json" with all requests related data
      "created": "2023-05-04T08:52:11.016Z",
      "sortNum": 65000,
      "folders": []
    },
    {
      "_id": "63e43c94-0b3f-4456-86f6-01de3f29c8e9",
      "colName": "My Test Collection 4",
      "requestsFolder": "./collections/customCollectionFolder/my-test-collection-4", -> contains one file "thunderclient.json" with all requests related data
      "created": "2023-05-04T08:52:11.016Z",
      "sortNum": 65000,
      "folders": []
    }
]
```

Hope this makes sense.
Thanks in advance!

**Comment by rangav** [comment] 2023-05-24 14:43
Hi @joaonunogomes thanks for the feedback, we plan implement something similar to what you suggested. Will provide more details when working on this feature

**Comment by joaonunogomes** [comment] 2023-05-24 14:51
> we plan implement something similar to what you suggested. Will provide more details when working on this feature

@rangav Awesome! Do you have an expected date for that? 
Also, if you need contributions fell free to ask.

**Comment by rangav** [comment] 2023-05-24 15:14
ETA by the end of June

**Comment by rangav** [comment] 2023-06-16 09:48
Hi All, Started working on this feature.

New file structure

- Each Env and Collection will be in a separate file
- Environment file name format `tc_env_{uniquieID}.json`
- Collection file name format `tc_col_{uniquieID}.json`
- When you rename of collection or environment name, the file names wont change
```
tc_env_3485d83939.json
tc_env_833h7s9334.json
tc_col_4938922938.json
tc_col_7829499jhs9.json
```

Let me know your feedback..

**Comment by rangav** [comment] 2023-06-16 14:25
@cw1934  In VS Code Explorer, you work with files directly, so you name them properly, like `customerData.js` etc. In TC you will work with **Extension UI**, where the collection name will be `Customer's Data 2023`, and the following process needs to be done:

1. The collection/env name needs to be converted to the slug `tc_col_customer_data_2023.json`
2. If the name is too long, then we have to shorten it.
3. Renaming a collection/environment name causes a change in the git file. If you don't stage it before checking in, the history may be lost.

If you don't see any issues with the above `point 3`, then I can implement it as mentioned in `points 1,2`.

**Comment by cw1934** [comment] 2023-06-16 15:46
@rangav

1. Agreed, some sanitation of the file name would have to be done in order to make sure it would follow restrictions on the applicable OS it's running on.  
2. Also agreed, trimming the file name would need to be accounted for, but hopefully a rare case that there is a collection/environment name over ~245 characters.  
3. I'm fine with this, and would even go as far as saying that this would be the expected behavior for any who use Git.

Thanks very much!

**Comment by rangav** [comment] 2023-06-16 15:59
@cw1934 how we deal with non-english collection names like Japanese, Korean etc..?

**Comment by rangav** [comment] 2023-06-16 17:49
Looks like this library can handle
https://www.npmjs.com/package/slug

**Comment by rangav** [comment] 2023-06-23 21:36
Hi All, I finished the development of this feature. Will upload `vsix` file here for testing tomorrow.

Let me know who is available to test and give feedback?

**Comment by rangav** [comment] 2023-06-25 17:22
Please find the `vsix` file to test the new database design.

- [vscode-thunder-client-2.7.8.vsix.zip](https://github.com/rangav/thunder-client-support/files/11860351/vscode-thunder-client-2.7.8.vsix.zip)

#### Please test for the following use cases and let me know your feedback.

- Test for the long collection or env name
- Test for the same collection name
- Test rename collection or environment
- Test a large number of collections

**Comment by rangav** [comment] 2023-06-25 20:50
Please find the `vsix` file to test the new database design.

- [vscode-thunder-client-2.7.8.vsix.zip](https://github.com/rangav/thunder-client-support/files/11860796/vscode-thunder-client-2.7.8.vsix.zip)

#### Please test for the following use cases and let me know your feedback.

- Test for the long collection or env name
- Test for the same collection name
- Test rename collection or environment
- Test a large number of collections

**Comment by joaonunogomes** [comment] 2023-06-26 09:32
Hi,
Sorry if I'm late. Just noticed these notifications.
I get the idea behind the decision of having files with the Ids, however, it would be great if each person/team can organize the files as they want. 
I see two possible approaches here:

1.  For example, you could add a setting so we can set the collection file location and the environment file location. 
2. Take leverage of the prefixes `tc_col` and `tc_env` and automatically locate all collection and environment files inside the project.

If I may, I would like to vote on approach 2, to enable teams to organize their files as they please.
Having everything in the root file may become very unorganized for bigger projects.

Regarding your request, I was able to test the following scenarios:
- Test for the same collection name ✅ 
- Test rename collection or environment ✅ 
- Test a large number of collections ✅ 
    - Thunderclient automatically break my collections in several files, everything seems to be working so far

**Comment by rangav** [comment] 2023-06-26 09:39
@joaonunogomes thanks for testing and providing feedback.

We already have a setting for approach 2 that you requested. Use the setting `Workspace Relative Path` - see below image

<img width="943" alt="Screenshot 2023-06-26 at 10 36 18" src="https://github.com/rangav/thunder-client-support/assets/8637550/c3a187d2-dba8-43f0-a460-514367907292">

**Comment by joaonunogomes** [comment] 2023-06-26 10:12
With the `vsix` you sent we have the following:
```
/thunder-tests
    /tc_col_COL1.json
    /tc_col_COL2.json
    /tc_col_COL3.json
    /tc_col_COL4.json
    /tc_col_COL5.json
    /tc_env_ENV1.json
    /tc_env_ENV2.json
    /tc_env_ENV3.json
    /tc_env_ENV4.json
    /tc_env_ENV5.json
```

From what I could get from the existing settings (`Workspace Relative Path`), it seems it only enables a way to customize the location of the thunderclient files (`Workspace Path`). What I was suggesting above was something that could enable the following:
```
/thunder-tests
     /collections
        /tc_col_COL1.json
        /tc_col_COL2.json
        /tc_col_COL3.json
        /tc_col_COL4.json
        /tc_col_COL5.json
    /environments
        /tc_env_ENV1.json
        /tc_env_ENV2.json
        /tc_env_ENV3.json
        /tc_env_ENV4.json
        /tc_env_ENV5.json
```

or even:

```
/thunder-tests
     /collections
        /someFolderToOrganizeFiles
           /tc_col_COL1.json
           /tc_col_COL2.json
        /tc_col_COL3.json
        /tc_col_COL4.json
        /tc_col_COL5.json
    /environments
        /tc_env_ENV1.json
        /tc_env_ENV2.json
        /tc_env_ENV3.json
        /tc_env_ENV4.json
        /tc_env_ENV5.json
```


Is this possible?

**Comment by rangav** [comment] 2023-06-26 10:20
@joaonunogomes now I understood.

The below is possible, and the other suggestion is too complicated.
```
/thunder-tests
     /collections
        /tc_col_COL1.json
        /tc_col_COL2.json
        /tc_col_COL3.json
        /tc_col_COL4.json
        /tc_col_COL5.json
    /environments
        /tc_env_ENV1.json
        /tc_env_ENV2.json
        /tc_env_ENV3.json
        /tc_env_ENV4.json
        /tc_env_ENV5.json
```

**Comment by joaonunogomes** [comment] 2023-06-26 10:28
Yes, I get the other is too complicated and too much magical as well. Splitting it into a `collections` folder and a `environments` will also make the files more organized. If you can do that I don't see any issues :)

**Comment by rangav** [comment] 2023-06-26 10:36
Sure will upload a new updated `vsix` file later today with your suggestion.

**Comment by rangav** [comment] 2023-06-26 11:20
@joaonunogomes one question about acitivity/history file thunderActivity.json.

- Where should be the activity file located - root or collections folder?

```
/thunder-tests
     /collections
        /tc_col_COL1.json
        /tc_col_COL2.json
        /tc_col_COL3.json
        /tc_col_COL4.json
        /tc_col_COL5.json
    /environments
        /tc_env_ENV1.json
        /tc_env_ENV2.json
        /tc_env_ENV3.json
        /tc_env_ENV4.json
        /tc_env_ENV5.json
thunderActivity.json
```

**Comment by rangav** [comment] 2023-06-27 11:05
This feature is now implemented and published to the marketplace, please update to `v2.8.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.8.0

Please let me know your feedback.

**Comment by rangav** [comment] 2023-06-27 11:06
In the next update, we will add support for Multi-root workspaces.

**Closed by rangav** 2023-06-27 11:05 UTC
Labels: feature request, Priority

**Comment by rangav** [comment] 2023-07-04 04:48
Hi all, any feedback on the new separated database files? 

Is it better now dealing with git merge?

**Comment by cw1934** [comment] 2023-07-05 16:54
The changes have been helpful.  So far, so good.  Thanks for the changes!

**Comment by rangav** [comment] 2023-07-07 15:43
`Multi-root workspaces` are now supported, please update to v2.9.0

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.9.0

Please test and let me know your feedback.

**Comment by rangav** [comment] 2023-07-07 16:42
- You can load request data from different workspace easily.

<img width="621" alt="Screenshot 2023-07-07 at 17 38 01" src="https://github.com/rangav/thunder-client-support/assets/8637550/b359bd26-8206-47c4-bde2-58de0104d204">

**Comment by anantanandgupta** [comment] 2023-07-08 04:58
Thanks

**Comment by rangav** [comment] 2023-07-10 18:51
Hi all, did you test `muti -root workspace` feature?

any feedback? Is it working as you expected?

**Comment by anantanandgupta** [comment] 2023-07-11 05:23
Not yet ... I actually have moved to other tool for the current project
because of the issue, but i will try it again soon and let you know.

**Comment by rangav** [comment] 2024-03-25 07:53
We are planning for `splitting collection` into multiple request files to reduce merge conflicts - https://github.com/thunderclient/thunder-client-support/issues/1507

Can you please let me know your feedback

**Comment by rangav** [comment] 2024-05-15 11:04
We have implemented a **new database design** to reduce merge conflicts. 

Update extension to [v2.23.0](https://github.com/thunderclient/thunder-client-support/releases/tag/v2.23.0) and follow the instructions in the below link

https://github.com/thunderclient/thunder-client-support/releases/tag/v2.23.0

Please upgrade to the new format and let us know your feedback.
