### ISSUE TITLE
Import from OpenAPI 3.0 / Swagger

### ISSUE THREAD

**Issue by reganheath** [rangav/thunder-client-support#223] opened 2021-06-23 14:08 UTC
Our services publish their request schema using a OpenAPI 3.0 json schema document.  It would be amazing if I could import from this, creating collections and requests with placeholder values.

I could then, trivially, duplicate and edit these requests for each specific test case I need, creating a complete test suite.

It would certainly beat importing them all by hand.

**Comment by rangav** [comment] 2021-06-23 14:25
Hi @reganheath this is in the roadmap, not yet prioritised.

The library is available separately, open for contribution 
https://github.com/rangav/thunder-imports

**Comment by reganheath** [comment] 2021-06-23 14:30
My TypeScript is non-existent, sorry.

**Comment by rangav** [comment] 2021-06-24 04:51
duplicate of #84

**Closed by rangav** 2021-06-24 04:51 UTC
