### ISSUE TITLE
Pre-request script feature to run before executing API.

### ISSUE THREAD

**Issue by IrshadSalik** [rangav/thunder-client-support#234] opened 2021-06-28 11:29 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Implementation:**

**Comment by rangav** [comment] 2021-06-28 11:40
Hi @IrshadSalik duplicate of #16

**Closed by rangav** 2021-06-28 11:40 UTC
