### ISSUE TITLE
Feature: Import collection from YAML

### ISSUE THREAD

**Issue by kowalski7cc** [rangav/thunder-client-support#431] opened 2022-01-03 08:59 UTC
At the moment, OpenAPI YAML files can't be imported as only JSON import is supported.

**Comment by rangav** [comment] 2022-01-03 09:18
Hi @kowalski7cc thanks for the feedback, will add to roadmap 

alternatively you can import yaml file  to postman and then export to json format, so you can import to Thunder Client

**Comment by rangav** [comment] 2022-01-15 21:05
I am closing this issue, as it's duplicate of #84

**Closed by rangav** 2022-01-15 21:05 UTC
Labels: feature request
