### ISSUE TITLE
Keep opened tabs when VS Code restarts.

### ISSUE THREAD

**Issue by nachokhan** [rangav/thunder-client-support#1102] opened 2023-04-04 21:03 UTC
It would be nice if, once VS Code is closed (for whatever reason), the ThunderClient tabs that were open before closing VS Code remain open once VS Code is open again

**Describe alternatives you've considered**
I go throught every request I need and double-click then again to reopen.

**Your Team Size Using TC:**
Just me

**Comment by rangav** [comment] 2023-04-05 03:47
Thanks @nachokhan for the feedback

Duplicate of #680

**Closed by rangav** 2023-04-05 03:47 UTC
Labels: feature request

**Comment by rangav** [comment] 2024-04-25 06:07
This feature has been implemented and published to the marketplace. Please update to `v2.21.15`.

You can see all the features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.21.15

Please test it and let me know your feedback
