### ISSUE TITLE
Thunder Client stopped returning data

### ISSUE THREAD

**Issue by erickemde** [rangav/thunder-client-support#620] opened 2022-06-13 16:45 UTC
**Describe the bug**
When I run a POST, TC has stopped returning data. This was a request that was working fine, but now doesn't. Instead of the expected JSON statement, the Response tab shows "Processing ... Cancel Request" - It doesn't return data no matter how long you wait.
Also, you cannot actually cancel the request.
The same request works when I run it on Postman.
I have tried:
- Deactivating/Reactivating the extension
- Uninstalling/Reinstalling the extension
- Opening the VS Code Developer Tools

When I open the developer tools, I see the following error as soon as I open the TC extension:

`main.bundle.js:1 Uncaught SyntaxError: Invalid regular expression: /(?:({{(?:+CCEHIP_NCIPC_OSP_Share-FC|+CCEHIP_NCIPC_Share-fc|+CCID_NCPDCID_DGMQ|+CDC_IT_R&D|+CSELS_General_Data_Hub-RO|+My_Large_Workspace|+NCIPC_Darpi_Speb-FC|+NCIPC_Informatics_Support-FC|+OA_DHS_HIBR_SAG-RO|+OCIO_SCA_DEV_MTG_REC-RO|+OCOO_HRO_Projects-RO|+OD_HCRMO_CDCU_Training-FC|+OD_HCRMO_LDIITS-RO|+OD_MASO_External_Share-RO|+OD_OCOO_HRO_SP_Share-RO|+OD_OWCD_ELearning_Content|+OWCD_TCD_Transfer-FC|+OWCD_Video|ALLUSERSPROFILE|APPDATA|APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL|CDC_Login|CDC_Login_Version|CDC_PIVCheck_Version|ChocolateyInstall|CHROME_CRASHPAD_PIPE_NAME|CommonProgramFiles|CommonProgramFiles(x86)|CommonProgramW6432|COMPUTERNAME|ComSpec|deployment.expiration.check.enabled|DriverData|ELECTRON_RUN_AS_NODE|EXSERVER|HOMEDRIVE|HOMEPATH|LOCALAPPDATA|LOGONSERVER|MyDocs|NUMBER_OF_PROCESSORS|OneDrive|OneDriveCommercial|ORIGINAL_XDG_CURRENT_DESKTOP|OS|Path|PATHEXT|PROCESSOR_ARCHITECTURE|PROCESSOR_IDENTIFIER|PROCESSOR_LEVEL|PROCESSOR_REVISION|ProgramData|ProgramFiles|ProgramFiles(x86)|ProgramW6432|PSModulePath|PUBLIC|PyCharm Community Edition|RTOOLS40_HOME|SESSIONNAME|SystemDrive|SystemRoot|TEMP|TMP|UATDATA|USERDNSDOMAIN|USERDOMAIN|USERDOMAIN_ROAMINGPROFILE|USERNAME|USERPROFILE|VSCODE_AMD_ENTRYPOINT|VSCODE_CODE_CACHE_PATH|VSCODE_CWD|VSCODE_HANDLES_UNCAUGHT_ERRORS|VSCODE_IPC_HOOK|VSCODE_IPC_HOOK_EXTHOST|VSCODE_LOG_NATIVE|VSCODE_LOG_STACK|VSCODE_NLS_CONFIG|VSCODE_PID|VSCODE_PIPE_LOGGING|VSCODE_VERBOSE_LOGGING|windir|Node_URL|BI_URL|SAS_API)+}}|{{#(?:guid|bool|enum|string|randomString|number|randomNumber|email|randomEmail|date|dateISO)+}}|({{#number(?:, ?(?:[0-9])+ ?)*}})|({{#date(?:, ?'(?:[^a-zA-Z0-9]|X|Y|M|D|h|m|s|f)+' ?)?}}))|(.))/: Nothing to repeat
    at new RegExp (<anonymous>)
    at new r (main.bundle.js:1:83958)
    at u.ace.define.getTokenizer (main.bundle.js:1:101946)
    at E (main.bundle.js:1:397532)
    at HTMLDocument.<anonymous> (main.bundle.js:1:399195)
    at x (main.bundle.js:1:421419)
    at HTMLDocument.<anonymous> (main.bundle.js:1:421596)`

**To Reproduce**

1. Open the extension in the sidebar.
2. Submit a request

**Expected behavior**
Returns a JSON statement

**Platform:** 
 - OS: Windows 2019
 - vscode version: 1.66.1
 - extension version: 1.16.4

**Solution:**
No.
Thanks for doing this extension. I much prefer it to Postman.

**Comment by rangav** [comment] 2022-06-13 16:55
@erickemde thanks for reporting the issue 

can you update vscode to latest version 1.68 and test again

**Comment by rangav** [comment] 2022-06-14 05:02
Closing as it's duplicate of #619

**Closed by rangav** 2022-06-14 05:02 UTC
Labels: bug
