### ISSUE TITLE
Let me hide the request timestamp

### ISSUE THREAD

**Issue by Tyriar** [rangav/thunder-client-support#729] opened 2022-08-18 20:33 UTC
**Is your feature request related to a problem? Please describe.**

The `x mins/hours/etc. ago` line in the request list is just noise to me and ends up adding a scroll bar to the tree.

![image](https://user-images.githubusercontent.com/2193314/185489247-f3cee60c-c307-4d2c-8da8-b01bb2b5531c.png)

**Describe the solution you'd like**

I'd love the ability to hide it, could there be a setting for this?

**Comment by rangav** [comment] 2022-08-19 03:11
Duplicate of #577

**Closed by rangav** 2022-08-19 03:11 UTC
Labels: feature request
