### ISSUE TITLE
Signature parameter not filled in automatically

### ISSUE THREAD

**Issue by xilopaint** [rangav/thunder-client-support#902] opened 2022-11-30 14:03 UTC
I'm trying to use [this Postman collection](https://github.com/binance/binance-api-postman). It works good in Postman but in Thunder Client I get this response for the `/api/v3/account` endpoint in the `Binance spot API` collection:

```json
{
  "code": -1105,
  "msg": "Parameter 'signature' was empty."
}
```

The signature parameter is an environment variable. In Postman we can leave it empty as well as the timestamp environment variable and they are filled in automatically (you just need to fill your API key and secret in the environment), but the same doesn't seem to work in Thunder Client.

**Comment by rangav** [comment] 2022-11-30 14:05
Hi @xilopaint thanks for creating the feature request.

I never used that feature, can you let me know how the signature needs to be calculated?

What is the request name in that collection?

**Comment by rangav** [comment] 2022-11-30 14:33
The signature and timestamp are not auto-generated, they are using a pre-request script, if you open the collection in postman you will see it.

```javascript
const ts  = Date.now();
pm.environment.set("timestamp", ts);

let paramsObject = {};

const binance_api_secret = pm.environment.get("binance-api-secret");

const parameters = pm.request.url.query;

parameters.map((param) => {
    if (param.key != 'signature' && 
        param.key != 'timestamp' && 
        !is_empty(param.value) &&
        !is_disabled(param.disabled)) {
            paramsObject[param.key] = param.value;
            //console.log(encodeURIComponent(param.value));
            //pm.environment.set(param.key, encodeURIComponent(param.value));
    }
})
        
Object.assign(paramsObject, {'timestamp': ts});

if (binance_api_secret) {
    const queryString = Object.keys(paramsObject).map((key) => {
        return `${key}=${paramsObject[key]}`;
    }).join('&');
    console.log(queryString);
    const signature = CryptoJS.HmacSHA256(queryString, binance_api_secret).toString();
    pm.environment.set("signature", signature);
}


function is_disabled(str) {
    return str == true;
}

function is_empty(str) {
    if (typeof str == 'undefined' ||
        !str || 
        str.length === 0 || 
        str === "" ||
        !/[^\s]/.test(str) ||
        /^\s*$/.test(str) ||
        str.replace(/\s/g,"") === "")
    {
        return true;
    }
    else
    {
        return false;
    }
}

```

You can do something similar using Custom Filters in Thunder Client.
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#custom-filters

**Comment by rangav** [comment] 2022-11-30 15:28
Postman script is different from Thunder Client.

May be I can try to convert this to Thunder Client format if you want, when I have free time.

**Comment by xilopaint** [comment] 2022-11-30 16:27
I'll try it myself as an exercise.

**Comment by rangav** [comment] 2022-11-30 17:54
For Response assertions or Test cases
https://github.com/rangav/thunder-client-support#testing

**Comment by xilopaint** [comment] 2022-11-30 21:29
@rangav I don't know JavaScript but as far as I understand the following snippet is enough to set the value for the `timestamp` environment variable:

```javascript
const ts  = Date.now();
pm.environment.set("timestamp", ts);
```

How could I do it in Thunder Client?

**Comment by xilopaint** [comment] 2022-12-02 11:25
> Then you can use in env variable as `{{timestamp | getTimestamp}}`

How can I test the value assigned to this env variable in the Tests tab?

**Comment by rangav** [comment] 2022-12-02 11:36
You can see in Logs in `Output` window, whether values are sent in request

**Comment by rangav** [comment] 2022-12-05 05:58
We now have feature to run Custom Filter directly in Pre-Run tab similar to pre request scripting.

So need to use it as `{{timestamp | getTimestamp}}`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.1.0

Please let me know your feedback.

**Comment by rangav** [comment] 2022-12-05 06:01
Here us updated example 

```javascript
function setVariablesFilter() {
   const ts  = Date.now();
   tc.setVar("timestamp", ts);

  // additional logic to calculate signature

 tc.setVar("signature", signatureValue);

}

module.exports = [setVariablesFilter]
```

**Comment by lfosborne** [comment] 2022-12-22 18:13
Hi.  Thank you for adding pre-request script like functionality as I use it extensively.  I am working with your sample custom-filters.js file but cannot get anything to display in the Select Custom Filter drop down on the Pre Run tab.  Am I missing a step to make the collection aware of the custom filter? 
![image](https://user-images.githubusercontent.com/114301910/209199299-6767fef7-254a-432a-885e-38b604e24da6.png)

**Comment by rangav** [comment] 2022-12-22 18:19
@lfosborne did you follow this steps
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#custom-filters

In custom script file, don’t forget `module.exports` line

**Comment by lfosborne** [comment] 2022-12-22 18:30
I somehow missed the Collection Settings.  I have found them now.  Thank you so much for the super fast reply!  So far I am loving Thunder Client!  Thanks again.

**Comment by rangav** [comment] 2022-12-22 18:45
@lfosborne glad you like extension, feel free to reach out if you have any further questions

**Comment by rangav** [comment] 2022-12-22 21:27
I am closing this issue, as its not a bug, but you can continue conversation if you have any questions.

**Closed by rangav** 2022-12-22 21:27 UTC
Labels: bug
