### ISSUE TITLE
Collection requests don't run in a defined order

### ISSUE THREAD

**Issue by AlekStyk** [rangav/thunder-client-support#1425] opened 2023-11-27 19:00 UTC
**Describe the bug**
Requests order defined in a collections **folder** is different from order displayed after **Run all** on a selected folder.
Any modification to a collections **folders** requests (manual rearrangement, duplication or removal) ends with the same incorrect final order of requests after **Run all**.
Only way to fix this behavior is to remove problematic folder along with every request inside.

**To Reproduce**
1. Add a new collection.
2. Add a new folder inside a collection.
3. Add any number of new requests (greater than 1).
4. Use **Run all** and verify the order of requests.

There is no specific way to always reproduce this problem. I have not been able to identify the cause.
It has happened to multiple folders in the same collection which had over 900 requests inside.
I attach the photo of a collection where the defined order is POST - DELETE - POST - DELETE... but final order after **Run all** is different.

![obraz](https://github.com/rangav/thunder-client-support/assets/121045962/fdb1a69b-cb38-4848-9617-c4d027d35bdf)

**Expected behavior**
Order of requests defined in a collections folder is the same as order of requests after **Run all**.

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.84.2
 - extension version: v2.16.2

**Are you using the free version/paid version/trial:**
Paid version

**Comment by rangav** [comment] 2023-11-27 19:02
Thanks @AlekStyk for reporting the issue, will look into it.

can you please confirm your subscription using below form, Thanks.
https://www.thunderclient.com/contact

**Comment by rangav** [comment] 2023-11-27 19:14
I just now verified it, the order is correct to me

<img width="972" alt="Screenshot 2023-11-27 at 19 13 35" src="https://github.com/rangav/thunder-client-support/assets/8637550/58b9b8bc-0bcb-418e-8877-52ca44ac3bb0">

**Comment by rangav** [comment] 2023-12-12 09:38
I am closing this issue as we cannot re-produce the issue, feel free to continue the discussion.

**Closed by rangav** 2023-12-12 09:38 UTC
Labels: bug

**Comment by AlekStyk** [comment] 2024-04-22 11:33
Hello!
Unfortunately, the issue still persists. The issue is annoying and appears more and more often when there are a very large number of requests in the collection.
However, I have further verified the problem.

The problem is with sorting requests in a folder. Upon verifying the sortNum in the JSON file, it is noticeable that values are being incorrectly assigned.
The most often occurs when I create requests by duplicating them. And then, when I try to add more requests using the "New request" option.

I attach the photo of a collection where the requests arranged in the folder are not sorted the same way in **Run all**. Requests that should be at the end in **Run all** are at positions 5 and 7, which is not correct.

![test](https://github.com/thunderclient/thunder-client-support/assets/121045962/c0690bec-a0b8-4b0b-a0d4-301c0cc39028)

Thank you!

**Comment by rangav** [comment] 2024-04-22 11:42
@AlekStyk I think its to schedule a call to address this issue.

Can you please let me know your availability using below form
https://www.thunderclient.com/contact

**Comment by AlekStyk** [comment] 2024-04-23 19:05
Unfortunately, I wont be able to show you an example from my project, as these are sensitive data.
However, I managed to replicate this issue locally using some random data. 

I am sending a json file of the collection in the attachment. Please follow my steps to reproduce the issue.
[thunder-collection_test.json](https://github.com/thunderclient/thunder-client-support/files/15081615/thunder-collection_test.json)

1. Export the json file to a new project.
2. Go to the last requests in the _order test_ folder.
3. **Duplicate** the last two requests twice:
<img src="https://github.com/thunderclient/thunder-client-support/assets/121045962/f2f2b19e-c858-4e07-adb6-510dbacf09b9" width="200" height="200">

4. Then, using the **New Request** option, add a new test request:
<img src="https://github.com/thunderclient/thunder-client-support/assets/121045962/f3a63186-4fe7-4616-896a-696d27b701e9" width="200" height="200">

5.Verify the order after clicking **Run all**
<img src="https://github.com/thunderclient/thunder-client-support/assets/121045962/cf047384-1f99-4b37-8fd7-fc8518ef894d" width="500" height="200">

You can notice that the last request added using the Add Request option is not in the correct order.

My example is simple, but its easy to notice the rearrange. In a large project with many requests, the mixing up of requests is significantly worse.

**Comment by rangav** [comment] 2024-04-23 19:12
Thanks @AlekStyk for sharing info. will verify and get back to you.

**Comment by rangav** [comment] 2024-04-24 11:12
cant reproduce the error

<img width="742" alt="Screenshot 2024-04-24 at 12 11 11" src="https://github.com/thunderclient/thunder-client-support/assets/8637550/3b242e88-e92a-47ea-8b56-7b7df1e18e04">

**Comment by rangav** [comment] 2024-04-24 11:14
better to do a call and show me the bug using this test collection. ( don't need use your real collection )

**Comment by rangav** [comment] 2024-04-25 06:21
This bug is fixed and published to the marketplace. Please update to `v2.21.15`.

You can see all the features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.21.15

Please test it and let me know your feedback

**Comment by AlekStyk** [comment] 2024-04-29 09:34
I don't reproduce the issue anymore, it's ok! Thank you!

**Comment by rangav** [comment] 2024-04-29 09:41
Thanks @AlekStyk for the confirmation.
