### ISSUE TITLE
cannot set "text" into env variable

### ISSUE THREAD

**Issue by anakodok** [rangav/thunder-client-support#369] opened 2021-10-14 04:24 UTC
Get a string as a response from API url and try to set the whole response body into variable
![image](https://user-images.githubusercontent.com/7483401/137251962-da5d973d-1a1c-44f1-8554-37d011c4a30b.png)

set "text" instead of "json." setTo {{VARIABLE_NAME, global}}
![image](https://user-images.githubusercontent.com/7483401/137252005-85877540-f239-423c-8f0d-19732ac7060b.png)

but the variable not updated
try to change "text" into "header.server" the variable updated successfully.

i only have global env, no any other env

**Platform:** 
 - OS: macOS 11.6 (Big Sur)
 - vscode version: 1.60.2
 - extension version: 1.9.1

**Comment by rangav** [comment] 2021-10-14 06:30
Thanks @anakodok for reporting the issue, I will verify and get back to you

**Comment by golavr** [comment] 2021-11-19 11:41
having the same issue.
tried to create env variable ahead and w/o creating, both cases aren't working.

**Comment by solarcloud7** [comment] 2021-12-14 22:37
Same issue

**Comment by rangav** [comment] 2021-12-15 16:04
Hi Just tested the text response, its working for me

tested using this sample url
https://www.thunderclient.io/t/text
![image](https://user-images.githubusercontent.com/8637550/146221304-5aa83f31-2d0d-4996-abc1-e0570f24bf1e.png)

![image](https://user-images.githubusercontent.com/8637550/146221341-e44b3d0d-8676-41e2-bcce-4d388adae133.png)

**Comment by solarcloud7** [comment] 2021-12-15 20:18
Thanks for your fast reply @rangav!  Your sample works for me as well.   However when I do a POST, and my response is `Vyu2FlDYToWw4QkOGiBNTQAAAX2/uWx+`  I'm experiencing an error.  

![image](https://user-images.githubusercontent.com/758330/146258585-258004ca-9753-47fb-9cab-5eb83ebc1ae9.png)

This is the response:
![image](https://user-images.githubusercontent.com/758330/146258703-f4ddd115-da99-4643-81c5-426afd7fa785.png)

Maybe its the special characters that the convergepay api is using in their token?

**Comment by rangav** [comment] 2021-12-16 10:37
Hi @solarcloud7 

Test the your response, this is also working for me
https://www.thunderclient.io/t/text2

![image](https://user-images.githubusercontent.com/8637550/146355875-7994245d-99ba-45b9-8af1-6e5a25e6835a.png)

![image](https://user-images.githubusercontent.com/8637550/146355999-fe1c15a6-9de8-4f46-98f6-7675a81184af.png)

**Comment by rangav** [comment] 2021-12-16 10:39
Hi @anakodok 

tested your response as well, this is also working for me
https://www.thunderclient.io/t/text3

![image](https://user-images.githubusercontent.com/8637550/146356305-32531d51-7b27-4927-8554-89285c1a5230.png)

![image](https://user-images.githubusercontent.com/8637550/146356382-42ce2e71-d85a-4125-8ae4-5adeb6e2282d.png)

**Comment by solarcloud7** [comment] 2021-12-16 14:07
Awesome the string value is fine!    The only difference i see between my failed test and @rangav 's is the POST vs GET.   Would you be able to test it with post by any chance? Thank you for helping us troubleshoot this for us! We love this plugin!!!

**Comment by rangav** [comment] 2021-12-16 14:27
Yeah POST is also working for me, you can test yourself with the below url

https://www.thunderclient.io/t/text2

![image](https://user-images.githubusercontent.com/8637550/146390045-7f620019-b423-475e-b2ec-be993976edd2.png)

**Comment by rangav** [comment] 2021-12-16 14:31
@solarcloud7  if you want I can test your website url that has the issue, please share the details

**Comment by solarcloud7** [comment] 2021-12-16 21:47
Thank you for the offer, I really appreciate it!  I am developing a payment processing program using Elavon's Converge API.  I wouldn't mind sharing my demo credentials to reproduce what I am experiencing however, the API whitelists IP's as an added layer of security.  

Your demo's work flawlessly though!  As a test, I wanted to see if ~~postman~~ another program was able to save the response Body to an environment variable and it was able to do so.     My experience must be a rare edge case.   Would my response headers affect anything?  I can't think of anything else to help pin point what i'm failing at.

**Comment by rangav** [comment] 2021-12-17 04:26
Can you share screenshot of response headers?

**Comment by solarcloud7** [comment] 2021-12-17 16:17
Here we go.  Thanks again for taking time to help me.

![image](https://user-images.githubusercontent.com/758330/146575093-9d6b1eef-1139-4763-8098-fbbf65a58bf2.png)

**Comment by rangav** [comment] 2021-12-17 16:49
Thanks for sharing, looks like content type header is missing in the response, that might be issue.

**Comment by rangav** [comment] 2022-01-15 20:28
I am closing this issue, feel free to re-open if needed

**Closed by rangav** 2022-01-15 20:28 UTC

**Comment by solarcloud7** [comment] 2022-01-15 20:52
Sounds good.   Is there any way in the application to set the content type to raw text  by default if the content type is missing in the response header?  Sadly I am at the mercy of Converge to adjust their API and i'm not going to hold my breath for them to fix it =(

**Comment by rangav** [comment] 2022-01-15 20:56
Without content type header it might be difficult.

Sure will add more descriptive error. Thanks for feedback

**Comment by rangav** [comment] 2022-01-22 07:29
Hi All, released new update
Now it will allow `without content-type header` in response for json and text outputs

https://github.com/rangav/thunder-client-support/releases/tag/v1.10.0

please let me know if any feedback
