### ISSUE TITLE
Add streaming of response

### ISSUE THREAD

**Issue by Smyja** [rangav/thunder-client-support#1096] opened 2023-04-02 09:51 UTC
I'd like to see the output as its coming.

**Comment by rangav** [comment] 2023-04-02 11:07
Thanks @Smyja for the feedback. 

Duplicate of #3

**Closed by rangav** 2023-04-02 11:07 UTC
Labels: feature request

**Comment by rangav** [comment] 2024-03-04 14:35
This feature has been implemented and published to the marketplace. Please update to `v2.19.0`.

You can see all the features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.19.0

Please test it and let me know your feedback
