### ISSUE TITLE
Thunder Client forever updating database #581

### ISSUE THREAD

**Issue by Leonardoperrella** [rangav/thunder-client-support#836] opened 2022-10-13 13:41 UTC
same problem on version 1.20.0

**Comment by rangav** [comment] 2022-10-13 13:48
Hi @Leonardoperrella, is it working with previous version?

**Comment by Leonardoperrella** [comment] 2022-10-13 13:55
How to downgrade?

**Comment by Leonardoperrella** [comment] 2022-10-13 14:04
I found on https://www.alphr.com/vs-code-how-to-install-extensions/.

I've tryed 1.19.7 so far and still the problem
--

**Comment by rangav** [comment] 2022-10-13 14:52
Where is the thunder client request files stored? Can you please share a screenshot.

**Comment by jonathan-wdtl** [comment] 2022-10-13 23:08
I also have the same updating database message forever. Assume its same issue.

I'm running vscode on linux
Testing version rollbacks:
- Became functional again when i rolled back to 1.19.3.
- Switched to 1.19.5, still working.
- Broken same way when switched to 1.19.7
- Switched to 1.19.6, works again.
- Broken agan when i switched to 1.19.7 again.`

I've seen a bunch of folders, .config/Code/logs/Datecode/exthost1/output_logging_datecode/ which contain x-Thunder Client.log files. These all contain only one line: Sidebar Load Error: Cannot read properties of undefined (reading 'data')

Last modification dates to files in .config/Code/User/globalStorage/rangav.vscode-thunder-client:
Note: i haven't added any new collections etc in a while
`~/.config/Code/User/globalStorage/rangav.vscode-thunder-client$ ls -Ral
.:
total 76
drwxrwxr-x 5 jonathan jonathan  4096 Oct 14 11:45 .
drwxrwxr-x 7 jonathan jonathan  4096 Oct 14 11:46 ..
drwxrwxr-x 2 jonathan jonathan  4096 Apr 19 13:05 backup
drwxrwxr-x 2 jonathan jonathan  4096 Oct  5 08:59 files
drwxrwxr-x 2 jonathan jonathan  4096 Oct  5 08:59 res-files
-rw-rw-r-- 1 jonathan jonathan 25788 Jun 23 14:09 thunderActivity.json
-rw------- 1 jonathan jonathan  6328 Mar 23  2022 thunderclient.db
-rw-rw-r-- 1 jonathan jonathan  7645 Oct  4 15:22 thunderclient.json
-rw-rw-r-- 1 jonathan jonathan  1026 Jun 23 13:12 thunderCollection.json
-rw-rw-r-- 1 jonathan jonathan     2 Oct 14 11:45 thunderEnvironment.json
-rw------- 1 jonathan jonathan     0 Mar 23  2022 thunderLocalEnvironment.db
-rw-rw-r-- 1 jonathan jonathan     2 Oct 14 11:44 thunderLocalEnvironment.json

./backup:
total 40
drwxrwxr-x 2 jonathan jonathan  4096 Apr 19 13:05 .
drwxrwxr-x 5 jonathan jonathan  4096 Oct 14 11:45 ..
-rw------- 1 jonathan jonathan 14258 Mar 23  2022 thunderActivity.db
-rw------- 1 jonathan jonathan  6328 Mar 23  2022 thunderclient.db
-rw------- 1 jonathan jonathan   670 Mar 23  2022 thunderCollection.db
-rw------- 1 jonathan jonathan     0 Mar 23  2022 thunderEnvironment.db
-rw------- 1 jonathan jonathan     0 Mar 23  2022 thunderLocalEnvironment.db
-rw------- 1 jonathan jonathan   841 Mar 23  2022 thunderResponses.db

./files:
total 8
drwxrwxr-x 2 jonathan jonathan 4096 Oct  5 08:59 .
drwxrwxr-x 5 jonathan jonathan 4096 Oct 14 11:45 ..

./res-files:
total 8
drwxrwxr-x 2 jonathan jonathan 4096 Oct  5 08:59 .
drwxrwxr-x 5 jonathan jonathan 4096 Oct 14 11:45 ..
`

I've exported to postman format in a working version, then wiped .config/Code/User/globalStorage/rangav.vscode-thunder-client and imported in 1.20.0. Now working fine.

Directory structure after restoring from postman format:
~/.config/Code/User/globalStorage/rangav.vscode-thunder-client$ ls -Ral
.:
total 36
drwxrwxr-x 4 jonathan jonathan 4096 Oct 14 11:56 .
drwxrwxr-x 7 jonathan jonathan 4096 Oct 14 11:56 ..
drwxrwxr-x 2 jonathan jonathan 4096 Oct 14 11:56 files
drwxrwxr-x 2 jonathan jonathan 4096 Oct 14 11:56 res-files
-rw-rw-r-- 1 jonathan jonathan    2 Oct 14 11:55 thunderActivity.json
-rw-rw-r-- 1 jonathan jonathan 4472 Oct 14 11:56 thunderclient.json
-rw-rw-r-- 1 jonathan jonathan 1026 Oct 14 11:56 thunderCollection.json
-rw-rw-r-- 1 jonathan jonathan    2 Oct 14 11:55 thunderEnvironment.json

./files:
total 8
drwxrwxr-x 2 jonathan jonathan 4096 Oct 14 11:56 .
drwxrwxr-x 4 jonathan jonathan 4096 Oct 14 11:56 ..

./res-files:
total 8
drwxrwxr-x 2 jonathan jonathan 4096 Oct 14 11:56 .
drwxrwxr-x 4 jonathan jonathan 4096 Oct 14 11:56 ..

I took a backup of the content in that directory before wiping.
Have diff'd the config directories with meld and took a quick look through, nothing jumped out at me as the cause, but it was only a quick look. Searched a few of the files that were different for "data" but didn't find anything.

If theres something in particular I can check between the old and new config files, let me know.
If you want the config files that were causing getting stuck on the updating database screen, they currently contains passwords/other sensitive data, so i'll have to clean them up before I can upload.

**Comment by rangav** [comment] 2022-10-16 08:15
Thanks for sharing info, will look into it.

**Comment by rangav** [comment] 2022-10-16 08:35
I think have` .db and .json` files in same directory might be causing the issue. if you made copy of all files and remove all `.db` files then it should work.

**Comment by rangav** [comment] 2022-10-17 16:44
Shall I close the issue?

**Comment by jonathan-wdtl** [comment] 2022-10-17 21:22
I restored the old broken files. Confirmed issue was happening again. Confirming that removing all .db files fixes this.
Since you've provided a functional workaround, its probably fine to close this, though we don't have confirmation if this is actually what happened for OP?

**Comment by rangav** [comment] 2022-10-28 20:00
Closing this issue, feel free to re-open if needed

**Closed by rangav** 2022-10-28 20:00 UTC
Labels: bug
