### ISSUE TITLE
the body of the get request in undefined 

### ISSUE THREAD

**Issue by Houssem12-ai** [rangav/thunder-client-support#112] opened 2021-05-04 16:47 UTC
**Describe the bug**
when i try to get the GET request body in nodejs with req.body it shows that the json object that i received is undefined while it works well in in POSTMAN 

**To Reproduce**

**Expected behavior**

**Platform:** 
 - OS: 

**Solution:**

**Comment by rangav** [comment] 2021-05-04 16:49
Hi @Houssem12-ai duplicate of https://github.com/rangav/thunder-client-support/issues/112

**Closed by rangav** 2021-05-04 16:49 UTC
