### ISSUE TITLE
Unable to import collections from Postman

### ISSUE THREAD

**Issue by neeharikasadhu** [rangav/thunder-client-support#96] opened 2021-04-30 14:57 UTC
Tried to export the collection from Postman and Import to Thunder Client.
But getting the following error "Failed to import".
![Issue](https://user-images.githubusercontent.com/69256142/116713483-20e5ee80-a9d5-11eb-9968-ff94185a3d3c.PNG)

**Comment by neeharikasadhu** [comment] 2021-04-30 15:16
Hi Ranga,

I updated the version to 1.1.0 and tried. But getting same errors with
OAuth and import.
Also, for your reference, please find attached screenshot with the entries
I gave in the OAuth screen.

[image: image.png]

Thanks,
Neeharika.

**Comment by rangav** [comment] 2021-04-30 15:47
Image is not uploaded correctly, and can test import postman collection now

**Comment by neeharikasadhu** [comment] 2021-05-03 09:23
Stilll not able to import the collection from postman.
Updated to version : 1.2.0

Also, in your pervious message you mentioned to "Add callback URL to your server's trusted URL list" to use OAuth. How do I do that?

**Comment by rangav** [comment] 2021-05-03 10:03
what is your oauth provider name? can you upload sample postman file that has the issue i will test it, without any sensitive info.

below is the link how to do it for google - its called **authorized redirect urls** in google.
https://manifoldapp.org/docs/customizing/settings/google

**Comment by sojan-official** [comment] 2021-05-04 17:38
@rangav faced the issue today with the postman collection. 
extension version: 1.2.0

I was able to successfully import another collection though. 


[Chatwoot Application API v1.0.postman_collection.txt](https://github.com/rangav/thunder-client-support/files/6422964/Chatwoot.Application.API.v1.0.postman_collection.txt)

**Comment by rangav** [comment] 2021-05-04 18:33
Hi @sojan-official i will verify and get back to you

**Comment by fforregs** [comment] 2021-05-05 16:25
same issue with import postman collection? getting the following error "Failed to import".
version 1.2.0

**Comment by rangav** [comment] 2021-05-05 16:29
Hi @fforregs can you uploaded a sample postman file, without sensitive info if possible, I will verify

**Comment by fforregs** [comment] 2021-05-05 16:32
here you are:
[e199ca3f201aab7a5c67.zip](https://github.com/rangav/thunder-client-support/files/6428772/e199ca3f201aab7a5c67.zip)

**Comment by rangav** [comment] 2021-05-05 17:46
Hi @fforregs this looks like postman 2.0.0 format, can you export it in 2.1 format.
![image](https://user-images.githubusercontent.com/8637550/117185877-33479a00-add2-11eb-87c4-c31f27400179.png)

**Comment by castrix** [comment] 2021-05-06 01:21
I encounter the same issue, I'm using debian 10, and exported collection v2.1 from postman

**Comment by rangav** [comment] 2021-05-06 03:41
Hi @castrix can you uploaded a sample postman file, without sensitive info if possible, I will verify

**Comment by castrix** [comment] 2021-05-06 04:36
I'm sorry I can't but I will try to reproduce the problem

**Comment by rangav** [comment] 2021-05-06 04:51
Ok no problem thanks

**Comment by castrix** [comment] 2021-05-06 04:59
@rangav here I'm successfully reproduce the error
[reproduce.postman_collection.zip](https://github.com/rangav/thunder-client-support/files/6431844/reproduce.postman_collection.zip)

**Comment by castrix** [comment] 2021-05-06 05:03
I will create a new issue

**Comment by rangav** [comment] 2021-05-06 05:05
Hi @castrix  no need to create new issue

**Comment by rangav** [comment] 2021-05-06 05:08
Hi @castrix i know this problem, i have fixed that already, will release a new update today.

**Comment by castrix** [comment] 2021-05-06 05:09
thank you

**Comment by rangav** [comment] 2021-05-06 17:06
this is fixed in v1.2.1 details here https://github.com/rangav/thunder-client-support/releases/tag/1.2.1

**Closed by rangav** 2021-05-06 17:06 UTC

**Comment by rangav** [comment] 2021-05-07 11:35
Sure @fforregs, will update the documentation.
