### ISSUE TITLE
Import Environment from .env file

### ISSUE THREAD

**Issue by kousher-alam** [rangav/thunder-client-support#74] opened 2021-04-27 10:27 UTC
**Is your feature request related to a problem? Please describe.**
It is not related to any problem, but it will be better if we can import environment from .env file

**Describe the solution you'd like**
Just allow .env file file to browse and select, if someone select the env file then add all of the variable and value in the environment.

**Implementation:**
1. Read .env file 
2. Parse it 
3. Add the variable and value in the environment.

**Comment by rangav** [comment] 2021-04-28 05:52
Hi @kousher-alam will add to roadmap.

**Comment by wildhart** [comment] 2021-04-30 18:15
What if you have different .env files for different environments? E.g. we have `.env.development` and `.env.production`.

I think it would be good to be able to link a particular .env file with a particular Thunder environment, so I could connect `.env.development` to my DEV Thunder environment, etc.  Then whichever Thunder environment is selected as the default, it would load all variables from the selected .env file.

Another solution would be able to link specific variables to a particular .env file.  E.g. in the DEV environment you could create the variable `url` with `{{.env.development['API_URL'}}`, and in the LIVE environment you could define it as `{{.env.production['API_URL']}}`.  Then that would still fit with your current environment schema.

**Comment by rangav** [comment] 2021-05-03 12:24
Hi @kousher-alam what is content format of env file and is it common format for all developers or projects?

**Comment by kousher-alam** [comment] 2021-05-03 12:28
I think single .env is good enough. content format of the env file is [key]: [value] and it's same for all.

**Comment by rangav** [comment] 2021-05-03 13:06
these 2 articles has [key]=[valye] format
https://www.freecodecamp.org/news/nodejs-custom-env-files-in-your-apps-fa7b3e67abe1/
https://medium.com/the-node-js-collection/making-your-node-js-work-everywhere-with-environment-variables-2da8cdf6e786

**Comment by wildhart** [comment] 2021-05-03 18:28
I've only ever seen [key]=[value]

**Comment by rangav** [comment] 2021-05-03 18:53
Instead of import how about connecting and empty env on thunder client to env file on your git or any location.

Because if we import - you have to change in both places when you want to change some variable value.

**Comment by rangav** [comment] 2021-05-23 14:34
Hi All

Linking environment on thunder client to your workspace .env files seems to be good solution as suggested by @wildhart and others on youtube comments, also solve the problem of excluding secrets from git #79 

I never working with env files so want to clarity below questions.

- Where are the .env files stored in your workspace
- Do you checkin .env files to git? and how you share them with the team members.
- In Tests when we use `set env variable` feature, thunder client should update the .env file values?
- Will the Global environment variables #70 still applies to .env files too?

Appreciate if  you anyone can answer these questions

**Comment by wildhart** [comment] 2021-05-23 19:32
- .env files are stored in the root folder of a project, as per the requirements of https://www.npmjs.com/package/dotenv
- The are NOT checked into git.  They are shared with team members and backed up using other methods (USB stick, Teams message, etc).
- imo, tests should not update the .env file.  The project's .env file is normally for storing secrets and other environment specific variables.  Thunder client's `set env variable` feature is for temporary variables.  It should use it's own env variables for this.
- Regarding #70, the variables within .env files should be available to all thunder client tests, however any duplicate variable in a thunder client env variables should take precedence over a variable from .env.  So the .env file could have a secret which the project uses when running, but thunder client's env variables could have a different secret which is only used in the http tests.  It would still be useful to have a global thunder client env variables as well as environment specific variables so that you don't have to duplicate http test data which is can be used in different environments, as per my comment on #70.

**Comment by rangav** [comment] 2021-05-23 19:46
Thanks @wildhart for detailed answers, very helpful 👍

**Comment by exhuma** [comment] 2021-06-18 08:51
I agree with all points in https://github.com/rangav/thunder-client-support/issues/74#issuecomment-846612958

To add to this: `.env` files are very common across many programming languages and synergise well with the [12-Factor App Spec](https://12factor.net/). So I see real value in this feature.

I am not aware if there's a recommended "best-practice" to name env-files for local/dev/production names. The way I do this at the moment is to handle the following files (later files override older files):

* `.env` -- checked into git with no secrets (using fake example values instead). This provides a template for users and makes the app start-up even if some features break due to fake-values.
* `.env.development` -- **not** checked into git. Overrides default values used for development (secret keys e.t.c.)

IIRC, some frameworks also use `env.local` files for additional overrides.

I think the question whether a file is tracked in version control or not should not make a difference for thunder-client.

**Comment by rangav** [comment] 2021-06-18 08:58
Thanks @exhuma for adding your feedback 👍

**Comment by wildhart** [comment] 2021-06-18 09:39
Maybe you could let the user define their own paths to their `.env` files.  E.g., in my dev thunder env file I could define a variable `"@import"` with value `"/.env.development"`, and in my production thunder env file I could define it as `"/.env.production"`.  Allowing multiple `@import` variables could allow multiple `.env` files be imported, in order of precedence.

**Comment by rangav** [comment] 2021-07-09 08:57
Hi all, this feature will be part of next update v1.7.0, import of .env files

**Comment by rangav** [comment] 2021-07-13 11:49
This feature is now implemented in v1.7.0
https://github.com/rangav/thunder-client-support/releases/tag/1.7.0

**Closed by rangav** 2021-07-13 11:49 UTC
Labels: feature request

**Comment by exhuma** [comment] 2021-07-22 11:32
I can't get this to work. I also don't see anything about this in the docs. I have version 1.7.1 so that should be fine. But I can't figure out how to make it work.

**Comment by rangav** [comment] 2021-07-22 11:47
Hi @exhuma - steps below

* from Env tab click import 
* Select all files in filter option 
* select .env file

in Mac you need use cmd+Sft + . to see hidden files

let me know if it working or not

**Comment by exhuma** [comment] 2021-07-22 12:36
This works. But unfortunately this won't give us much of an "added value" to ThunderClient. Mainly because the import is manual.

Normally, .env files are interpreted at runtime (or startup-time) of the process in question.

For thunder-client I would expect it to load the .env file the moment a request is executed. So any changes in the env-file would be automatically taken into account.

That would reproduce the behaviour of other ".env" loaders and it would also avoid the necessity to communicate to the other team-members that the .env-file needs an update.

Making the update a manual process defeats the purpose of an env-file.

**Comment by rangav** [comment] 2021-07-22 13:17
@exhuma you are right, current implementation is import only, not linked to the .env file, will implement linking in the next update.

**Comment by ajaydwarkani** [comment] 2021-07-23 20:12
> @exhuma you are right, current implementation is import only, not linked to the .env file, will implement linking in the next update.

@rangav , any update on the above request to load .env file dynamically instead of import? This will also enable share my thunderEnvironment.db with team members which will only contain non-secrete values.

**Comment by rangav** [comment] 2021-07-23 20:19
Hi @ajaydwarkani linking/dynamic load will be part of next update

**Comment by ajaydwarkani** [comment] 2021-07-23 20:23
Looking forward to using this feature.

**Comment by rangav** [comment] 2021-07-23 20:28
FYI

The way linking will work is 
- create new env first
- Then open env variables view
- Here you will have option to select an .env file that you like to link to this environment 
- Manually adding variables form will be disabled if you link .env file

let me know any feedback

**Comment by exhuma** [comment] 2021-07-24 11:36
That sounds good. 

Actual usage of this will make this clearer. We are currently not _actively_ using it. I think the proposed solution with linked env-files will be the first iteration of ThunderClient that will make it usable for our team. Although I wouldn't be surprised if actual practical usage in a real-world environment turns up new ideas.

**Comment by rangav** [comment] 2021-07-26 13:40
**Linking .env file** feature is now implemented in v1.8.0

see all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.8.0

**Comment by rodriguescu** [comment] 2022-03-30 16:39
Does it work with relative paths? I tried in mac os and only absolute seem to work. The UI doesn't allow for relative paths, but you can work around it through exporting/importing. 
The problem with absolute paths is that then the environment can't be versioned. Anything that can be done?

**Comment by rangav** [comment] 2022-03-30 16:46
Hi @rodriguescu 

There are 2 options

- Import .env file -  This will just import the key/values from env file, path is not saved ( You can use Import menu from Env Tab )
- Link to .env file - This will link to an existing .env file in your git project, you just select the file, it save the relative path

Link to .env file instructions
![image](https://user-images.githubusercontent.com/8637550/160888150-eaec11b1-2101-4af3-bd2b-135f8569a2d9.png)

let me know if you have further questions.
