### ISSUE TITLE
Publish Thunder Client in OpenVSX

### ISSUE THREAD

**Issue by bitsper2nd** [rangav/thunder-client-support#268] opened 2021-07-16 01:41 UTC
Hi can you publish Thunder Client in [OpenVSX](https://open-vsx.org/)? It would be great for those of us that use [VSCodium](https://vscodium.com/) or [Onivim2](https://v2.onivim.io/#preorder) to not need to install the extensions manually.

**Comment by rangav** [comment] 2021-07-16 03:07
Hi @bitsper2nd duplicate of #30

**Closed by rangav** 2021-07-16 03:07 UTC

**Comment by bitsper2nd** [comment] 2021-07-16 03:12
Oh, sorry for that. Carry on.
