### ISSUE TITLE
Environment inheritance

### ISSUE THREAD

**Issue by reganheath** [rangav/thunder-client-support#221] opened 2021-06-23 13:02 UTC
I would like to be able to inherit environment variables into a new sub-environment.

Perhaps we can select an existing environment as "parent".

All variables from the parent are inherited by the child.  Any identical variables defined in the child override the parent.

If a child environment defines a variable using {{replacement}} tokens, these should resolve whether they exist in the parent or child.

Otherwise.. I have to duplicate environments, and then have a maintenance issue when I need to update a common variable.

**Comment by rangav** [comment] 2021-06-24 04:52
duplicate of #38

**Closed by rangav** 2021-06-24 04:52 UTC
