### ISSUE TITLE
Custom test set env variable encryp

### ISSUE THREAD

**Issue by yiyo1989** [rangav/thunder-client-support#210] opened 2021-06-18 23:48 UTC
**Is your feature request related to a problem? Please describe.**

I need to encrypt a key from the input parameters of the "query" before sending it to the service, but I can't find a way to do it currently. In postman if possible using the "Pre-request Script" option.
**Describe the solution you'd like**

**Describe alternatives you've considered**
The solution could be to enable in the option under test an additional option called "Pre-request Script" and enable a text to be able to place the script to assign value to the variables. In postman I can do it using the following sentence:

```
var plainText = pm.environment.get ('plainTextString');
var encrypted = CryptoJS.enc.Base64.stringify (plainText);

pm.environment.set ("myEncryptedRequestVariable", encrypted);

```
Of course, they need to include built-in functions to be able to use them like "CryptoJS" and other functions that postman uses as a base.

**Implementation:**
Link reference:

[EncodingVariablesPostman](https://stackoverflow.com/questions/43844192/encoding-variables-using-postman/49434499)

**Comment by rangav** [comment] 2021-06-19 08:52
Hi @yiyo1989 duplicate of #16

**Comment by rangav** [comment] 2021-06-19 08:53
Can you add these comments in the existing issue, so we can track in one place.

**Closed by rangav** 2021-06-19 08:53 UTC
