### ISSUE TITLE
Auth: Add support for `grant_type="refresh_token"`

### ISSUE THREAD

**Issue by jimmybutton** [rangav/thunder-client-support#669] opened 2022-07-19 15:54 UTC
First of all, I just wanted so say how much I love Thunder Client. It's such a great productivity tool!

I recently discovered the built-in options to generate OAuth 2 tokens. There are currently four options for `grant_type`. I'd like to be able to use `grant_type="refresh_token"` to generate an access token using that method.

Maybe I'm missing s.th. and it's already possible to do that using one of the other options. If so, please let me know. Many thanks!

**Comment by rangav** [comment] 2022-07-20 04:29
duplicate of #668

**Closed by rangav** 2022-07-20 04:29 UTC
Labels: feature request
