### ISSUE TITLE
new request not created in active split pane

### ISSUE THREAD

**Issue by rajinder-yadav** [rangav/thunder-client-support#144] opened 2021-05-12 09:18 UTC
**Describe the bug**

When the editor has split panes, clicking on the "New Request" should open the new request in the active pane. Currently it always open to the left most page.

This should be a configurable setting to default to splitting the pane, if it's not already and then opening the new request in the right most pane.

![snap-49](https://user-images.githubusercontent.com/439226/117948988-aa53c580-b2df-11eb-97f8-7b1df40a48b0.png)

**To Reproduce**

-Open a source file in the editor.
-Split the pave
-Click inside the right most pane to make it active.
-Open Thunder Client
-Click 
-New Request"

**Expected behavior**

New request page should be created in the active pane.

**Platform:** 
Operating System: openSUSE Tumbleweed 20210508
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.81.0
Qt Version: 5.15.2
Kernel Version: 5.12.0-2-default
OS Type: 64-bit
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: Radeon RX 570 Series

**Solution:**

**Comment by rangav** [comment] 2021-05-12 11:53
Hi @rajinder-yadav duplicate of #115

**Closed by rangav** 2021-05-12 11:53 UTC
