### ISSUE TITLE
OpenAPI support

### ISSUE THREAD

**Issue by juninhodeluca** [rangav/thunder-client-support#350] opened 2021-10-04 14:55 UTC
Hi, I just made some tests to use this amazing extension in real world projects and  was partially KO since all our REST documentation is based on openAPI, with a specs.yml file, which is not supported at the moment in collection / import
To by-pass, I should load the specs.yml collection into postman and from there export it again as json, which is a huge problem for dev-teams flow, since specs.yml is into repository and became updated eventually, while the json format not.
Anyways, it's a very amazing extension and I really enjoy it. Nice work!

**Comment by rangav** [comment] 2021-10-04 16:51
Hi @juninhodeluca open Api import support coming soon. If you like to contribute to this let me know.

**Comment by eladhaim22** [comment] 2021-10-17 13:51
i would love to contribute to this awesome project.

**Comment by rangav** [comment] 2022-01-15 21:04
I am closing this issue, as it's duplicate of #84

**Closed by rangav** 2022-01-15 21:04 UTC
