### ISSUE TITLE
Support preview for visual files such as images and pdfs

### ISSUE THREAD

**Issue by JonathanEspinosaLong** [rangav/thunder-client-support#229] opened 2021-06-24 17:37 UTC
**Is your feature request related to a problem? Please describe.**
PDF and image files appear as raw information in the response window. 

**Describe the solution you'd like**
For pdf and image files to be rendered correctly and not just look at the raw data of the file.

**Describe alternatives you've considered**
Something similar to the preview feature in the Insomnia client 

**Implementation:**

**Comment by rangav** [comment] 2021-06-24 18:02
Hi @JonathanEspinosaLong duplicate of #97

**Closed by rangav** 2021-06-24 18:02 UTC

**Comment by rangav** [comment] 2021-07-13 11:51
This feature is now implemented in v1.7.0
https://github.com/rangav/thunder-client-support/releases/tag/1.7.0

Supports only images, not pdf.
